// Code generated by ent, DO NOT EDIT.

package editablefiletask

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the editablefiletask type in the database.
	Label = "editable_file_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldImageConversationID holds the string denoting the image_conversation_id field in the database.
	FieldImageConversationID = "image_conversation_id"
	// FieldSourceGenerationID holds the string denoting the source_generation_id field in the database.
	FieldSourceGenerationID = "source_generation_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldClientTaskID holds the string denoting the client_task_id field in the database.
	FieldClientTaskID = "client_task_id"
	// FieldChatgptConversationID holds the string denoting the chatgpt_conversation_id field in the database.
	FieldChatgptConversationID = "chatgpt_conversation_id"
	// FieldCost holds the string denoting the cost field in the database.
	FieldCost = "cost"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the editablefiletask in the database.
	Table = "editable_file_tasks"
)

// Columns holds all SQL columns for editablefiletask fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldGroupID,
	FieldAPIKeyID,
	FieldImageConversationID,
	FieldSourceGenerationID,
	FieldAccountID,
	FieldKind,
	FieldStatus,
	FieldPrompt,
	FieldModel,
	FieldClientTaskID,
	FieldChatgptConversationID,
	FieldCost,
	FieldError,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultClientTaskID holds the default value on creation for the "client_task_id" field.
	DefaultClientTaskID string
	// ClientTaskIDValidator is a validator for the "client_task_id" field. It is called by the builders before save.
	ClientTaskIDValidator func(string) error
	// DefaultChatgptConversationID holds the default value on creation for the "chatgpt_conversation_id" field.
	DefaultChatgptConversationID string
	// ChatgptConversationIDValidator is a validator for the "chatgpt_conversation_id" field. It is called by the builders before save.
	ChatgptConversationIDValidator func(string) error
	// DefaultCost holds the default value on creation for the "cost" field.
	DefaultCost float64
)

// OrderOption defines the ordering options for the EditableFileTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByImageConversationID orders the results by the image_conversation_id field.
func ByImageConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageConversationID, opts...).ToFunc()
}

// BySourceGenerationID orders the results by the source_generation_id field.
func BySourceGenerationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceGenerationID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByClientTaskID orders the results by the client_task_id field.
func ByClientTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientTaskID, opts...).ToFunc()
}

// ByChatgptConversationID orders the results by the chatgpt_conversation_id field.
func ByChatgptConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatgptConversationID, opts...).ToFunc()
}

// ByCost orders the results by the cost field.
func ByCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCost, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
