// Code generated by ent, DO NOT EDIT.

package editablefiletask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldGroupID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// ImageConversationID applies equality check predicate on the "image_conversation_id" field. It's identical to ImageConversationIDEQ.
func ImageConversationID(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldImageConversationID, v))
}

// SourceGenerationID applies equality check predicate on the "source_generation_id" field. It's identical to SourceGenerationIDEQ.
func SourceGenerationID(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldSourceGenerationID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldAccountID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldKind, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldStatus, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldPrompt, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldModel, v))
}

// ClientTaskID applies equality check predicate on the "client_task_id" field. It's identical to ClientTaskIDEQ.
func ClientTaskID(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldClientTaskID, v))
}

// ChatgptConversationID applies equality check predicate on the "chatgpt_conversation_id" field. It's identical to ChatgptConversationIDEQ.
func ChatgptConversationID(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldChatgptConversationID, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldCost, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldError, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotNull(FieldGroupID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotNull(FieldAPIKeyID))
}

// ImageConversationIDEQ applies the EQ predicate on the "image_conversation_id" field.
func ImageConversationIDEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldImageConversationID, v))
}

// ImageConversationIDNEQ applies the NEQ predicate on the "image_conversation_id" field.
func ImageConversationIDNEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldImageConversationID, v))
}

// ImageConversationIDIn applies the In predicate on the "image_conversation_id" field.
func ImageConversationIDIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldImageConversationID, vs...))
}

// ImageConversationIDNotIn applies the NotIn predicate on the "image_conversation_id" field.
func ImageConversationIDNotIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldImageConversationID, vs...))
}

// ImageConversationIDGT applies the GT predicate on the "image_conversation_id" field.
func ImageConversationIDGT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldImageConversationID, v))
}

// ImageConversationIDGTE applies the GTE predicate on the "image_conversation_id" field.
func ImageConversationIDGTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldImageConversationID, v))
}

// ImageConversationIDLT applies the LT predicate on the "image_conversation_id" field.
func ImageConversationIDLT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldImageConversationID, v))
}

// ImageConversationIDLTE applies the LTE predicate on the "image_conversation_id" field.
func ImageConversationIDLTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldImageConversationID, v))
}

// ImageConversationIDIsNil applies the IsNil predicate on the "image_conversation_id" field.
func ImageConversationIDIsNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIsNull(FieldImageConversationID))
}

// ImageConversationIDNotNil applies the NotNil predicate on the "image_conversation_id" field.
func ImageConversationIDNotNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotNull(FieldImageConversationID))
}

// SourceGenerationIDEQ applies the EQ predicate on the "source_generation_id" field.
func SourceGenerationIDEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldSourceGenerationID, v))
}

// SourceGenerationIDNEQ applies the NEQ predicate on the "source_generation_id" field.
func SourceGenerationIDNEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldSourceGenerationID, v))
}

// SourceGenerationIDIn applies the In predicate on the "source_generation_id" field.
func SourceGenerationIDIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldSourceGenerationID, vs...))
}

// SourceGenerationIDNotIn applies the NotIn predicate on the "source_generation_id" field.
func SourceGenerationIDNotIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldSourceGenerationID, vs...))
}

// SourceGenerationIDGT applies the GT predicate on the "source_generation_id" field.
func SourceGenerationIDGT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldSourceGenerationID, v))
}

// SourceGenerationIDGTE applies the GTE predicate on the "source_generation_id" field.
func SourceGenerationIDGTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldSourceGenerationID, v))
}

// SourceGenerationIDLT applies the LT predicate on the "source_generation_id" field.
func SourceGenerationIDLT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldSourceGenerationID, v))
}

// SourceGenerationIDLTE applies the LTE predicate on the "source_generation_id" field.
func SourceGenerationIDLTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldSourceGenerationID, v))
}

// SourceGenerationIDIsNil applies the IsNil predicate on the "source_generation_id" field.
func SourceGenerationIDIsNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIsNull(FieldSourceGenerationID))
}

// SourceGenerationIDNotNil applies the NotNil predicate on the "source_generation_id" field.
func SourceGenerationIDNotNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotNull(FieldSourceGenerationID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotNull(FieldAccountID))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContainsFold(FieldKind, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContainsFold(FieldStatus, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContainsFold(FieldPrompt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContainsFold(FieldModel, v))
}

// ClientTaskIDEQ applies the EQ predicate on the "client_task_id" field.
func ClientTaskIDEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldClientTaskID, v))
}

// ClientTaskIDNEQ applies the NEQ predicate on the "client_task_id" field.
func ClientTaskIDNEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldClientTaskID, v))
}

// ClientTaskIDIn applies the In predicate on the "client_task_id" field.
func ClientTaskIDIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldClientTaskID, vs...))
}

// ClientTaskIDNotIn applies the NotIn predicate on the "client_task_id" field.
func ClientTaskIDNotIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldClientTaskID, vs...))
}

// ClientTaskIDGT applies the GT predicate on the "client_task_id" field.
func ClientTaskIDGT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldClientTaskID, v))
}

// ClientTaskIDGTE applies the GTE predicate on the "client_task_id" field.
func ClientTaskIDGTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldClientTaskID, v))
}

// ClientTaskIDLT applies the LT predicate on the "client_task_id" field.
func ClientTaskIDLT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldClientTaskID, v))
}

// ClientTaskIDLTE applies the LTE predicate on the "client_task_id" field.
func ClientTaskIDLTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldClientTaskID, v))
}

// ClientTaskIDContains applies the Contains predicate on the "client_task_id" field.
func ClientTaskIDContains(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContains(FieldClientTaskID, v))
}

// ClientTaskIDHasPrefix applies the HasPrefix predicate on the "client_task_id" field.
func ClientTaskIDHasPrefix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasPrefix(FieldClientTaskID, v))
}

// ClientTaskIDHasSuffix applies the HasSuffix predicate on the "client_task_id" field.
func ClientTaskIDHasSuffix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasSuffix(FieldClientTaskID, v))
}

// ClientTaskIDEqualFold applies the EqualFold predicate on the "client_task_id" field.
func ClientTaskIDEqualFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEqualFold(FieldClientTaskID, v))
}

// ClientTaskIDContainsFold applies the ContainsFold predicate on the "client_task_id" field.
func ClientTaskIDContainsFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContainsFold(FieldClientTaskID, v))
}

// ChatgptConversationIDEQ applies the EQ predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldChatgptConversationID, v))
}

// ChatgptConversationIDNEQ applies the NEQ predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDNEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldChatgptConversationID, v))
}

// ChatgptConversationIDIn applies the In predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldChatgptConversationID, vs...))
}

// ChatgptConversationIDNotIn applies the NotIn predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDNotIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldChatgptConversationID, vs...))
}

// ChatgptConversationIDGT applies the GT predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDGT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldChatgptConversationID, v))
}

// ChatgptConversationIDGTE applies the GTE predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDGTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldChatgptConversationID, v))
}

// ChatgptConversationIDLT applies the LT predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDLT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldChatgptConversationID, v))
}

// ChatgptConversationIDLTE applies the LTE predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDLTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldChatgptConversationID, v))
}

// ChatgptConversationIDContains applies the Contains predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDContains(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContains(FieldChatgptConversationID, v))
}

// ChatgptConversationIDHasPrefix applies the HasPrefix predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDHasPrefix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasPrefix(FieldChatgptConversationID, v))
}

// ChatgptConversationIDHasSuffix applies the HasSuffix predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDHasSuffix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasSuffix(FieldChatgptConversationID, v))
}

// ChatgptConversationIDEqualFold applies the EqualFold predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDEqualFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEqualFold(FieldChatgptConversationID, v))
}

// ChatgptConversationIDContainsFold applies the ContainsFold predicate on the "chatgpt_conversation_id" field.
func ChatgptConversationIDContainsFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContainsFold(FieldChatgptConversationID, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v float64) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldCost, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldContainsFold(FieldError, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.FieldNotNull(FieldExpiresAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EditableFileTask) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EditableFileTask) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EditableFileTask) predicate.EditableFileTask {
	return predicate.EditableFileTask(sql.NotPredicates(p))
}
