// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/editablefiletask"
)

// EditableFileTaskCreate is the builder for creating a EditableFileTask entity.
type EditableFileTaskCreate struct {
	config
	mutation *EditableFileTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EditableFileTaskCreate) SetCreatedAt(v time.Time) *EditableFileTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableCreatedAt(v *time.Time) *EditableFileTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EditableFileTaskCreate) SetUpdatedAt(v time.Time) *EditableFileTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableUpdatedAt(v *time.Time) *EditableFileTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EditableFileTaskCreate) SetDeletedAt(v time.Time) *EditableFileTaskCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableDeletedAt(v *time.Time) *EditableFileTaskCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *EditableFileTaskCreate) SetUserID(v int64) *EditableFileTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *EditableFileTaskCreate) SetGroupID(v int64) *EditableFileTaskCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableGroupID(v *int64) *EditableFileTaskCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *EditableFileTaskCreate) SetAPIKeyID(v int64) *EditableFileTaskCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableAPIKeyID(v *int64) *EditableFileTaskCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetImageConversationID sets the "image_conversation_id" field.
func (_c *EditableFileTaskCreate) SetImageConversationID(v int64) *EditableFileTaskCreate {
	_c.mutation.SetImageConversationID(v)
	return _c
}

// SetNillableImageConversationID sets the "image_conversation_id" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableImageConversationID(v *int64) *EditableFileTaskCreate {
	if v != nil {
		_c.SetImageConversationID(*v)
	}
	return _c
}

// SetSourceGenerationID sets the "source_generation_id" field.
func (_c *EditableFileTaskCreate) SetSourceGenerationID(v int64) *EditableFileTaskCreate {
	_c.mutation.SetSourceGenerationID(v)
	return _c
}

// SetNillableSourceGenerationID sets the "source_generation_id" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableSourceGenerationID(v *int64) *EditableFileTaskCreate {
	if v != nil {
		_c.SetSourceGenerationID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *EditableFileTaskCreate) SetAccountID(v int64) *EditableFileTaskCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableAccountID(v *int64) *EditableFileTaskCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *EditableFileTaskCreate) SetKind(v string) *EditableFileTaskCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EditableFileTaskCreate) SetStatus(v string) *EditableFileTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableStatus(v *string) *EditableFileTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *EditableFileTaskCreate) SetPrompt(v string) *EditableFileTaskCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *EditableFileTaskCreate) SetModel(v string) *EditableFileTaskCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableModel(v *string) *EditableFileTaskCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetClientTaskID sets the "client_task_id" field.
func (_c *EditableFileTaskCreate) SetClientTaskID(v string) *EditableFileTaskCreate {
	_c.mutation.SetClientTaskID(v)
	return _c
}

// SetNillableClientTaskID sets the "client_task_id" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableClientTaskID(v *string) *EditableFileTaskCreate {
	if v != nil {
		_c.SetClientTaskID(*v)
	}
	return _c
}

// SetChatgptConversationID sets the "chatgpt_conversation_id" field.
func (_c *EditableFileTaskCreate) SetChatgptConversationID(v string) *EditableFileTaskCreate {
	_c.mutation.SetChatgptConversationID(v)
	return _c
}

// SetNillableChatgptConversationID sets the "chatgpt_conversation_id" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableChatgptConversationID(v *string) *EditableFileTaskCreate {
	if v != nil {
		_c.SetChatgptConversationID(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *EditableFileTaskCreate) SetCost(v float64) *EditableFileTaskCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableCost(v *float64) *EditableFileTaskCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *EditableFileTaskCreate) SetError(v string) *EditableFileTaskCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableError(v *string) *EditableFileTaskCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *EditableFileTaskCreate) SetExpiresAt(v time.Time) *EditableFileTaskCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *EditableFileTaskCreate) SetNillableExpiresAt(v *time.Time) *EditableFileTaskCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the EditableFileTaskMutation object of the builder.
func (_c *EditableFileTaskCreate) Mutation() *EditableFileTaskMutation {
	return _c.mutation
}

// Save creates the EditableFileTask in the database.
func (_c *EditableFileTaskCreate) Save(ctx context.Context) (*EditableFileTask, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EditableFileTaskCreate) SaveX(ctx context.Context) *EditableFileTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EditableFileTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EditableFileTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EditableFileTaskCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if editablefiletask.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized editablefiletask.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := editablefiletask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if editablefiletask.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized editablefiletask.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := editablefiletask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := editablefiletask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := editablefiletask.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.ClientTaskID(); !ok {
		v := editablefiletask.DefaultClientTaskID
		_c.mutation.SetClientTaskID(v)
	}
	if _, ok := _c.mutation.ChatgptConversationID(); !ok {
		v := editablefiletask.DefaultChatgptConversationID
		_c.mutation.SetChatgptConversationID(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := editablefiletask.DefaultCost
		_c.mutation.SetCost(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EditableFileTaskCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EditableFileTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EditableFileTask.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "EditableFileTask.user_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "EditableFileTask.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := editablefiletask.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EditableFileTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := editablefiletask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "EditableFileTask.prompt"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "EditableFileTask.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := editablefiletask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientTaskID(); !ok {
		return &ValidationError{Name: "client_task_id", err: errors.New(`ent: missing required field "EditableFileTask.client_task_id"`)}
	}
	if v, ok := _c.mutation.ClientTaskID(); ok {
		if err := editablefiletask.ClientTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "client_task_id", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.client_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChatgptConversationID(); !ok {
		return &ValidationError{Name: "chatgpt_conversation_id", err: errors.New(`ent: missing required field "EditableFileTask.chatgpt_conversation_id"`)}
	}
	if v, ok := _c.mutation.ChatgptConversationID(); ok {
		if err := editablefiletask.ChatgptConversationIDValidator(v); err != nil {
			return &ValidationError{Name: "chatgpt_conversation_id", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.chatgpt_conversation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "EditableFileTask.cost"`)}
	}
	return nil
}

func (_c *EditableFileTaskCreate) sqlSave(ctx context.Context) (*EditableFileTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EditableFileTaskCreate) createSpec() (*EditableFileTask, *sqlgraph.CreateSpec) {
	var (
		_node = &EditableFileTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(editablefiletask.Table, sqlgraph.NewFieldSpec(editablefiletask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(editablefiletask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(editablefiletask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(editablefiletask.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(editablefiletask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(editablefiletask.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(editablefiletask.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.ImageConversationID(); ok {
		_spec.SetField(editablefiletask.FieldImageConversationID, field.TypeInt64, value)
		_node.ImageConversationID = &value
	}
	if value, ok := _c.mutation.SourceGenerationID(); ok {
		_spec.SetField(editablefiletask.FieldSourceGenerationID, field.TypeInt64, value)
		_node.SourceGenerationID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(editablefiletask.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(editablefiletask.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(editablefiletask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(editablefiletask.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(editablefiletask.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.ClientTaskID(); ok {
		_spec.SetField(editablefiletask.FieldClientTaskID, field.TypeString, value)
		_node.ClientTaskID = value
	}
	if value, ok := _c.mutation.ChatgptConversationID(); ok {
		_spec.SetField(editablefiletask.FieldChatgptConversationID, field.TypeString, value)
		_node.ChatgptConversationID = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(editablefiletask.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(editablefiletask.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(editablefiletask.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EditableFileTask.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EditableFileTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EditableFileTaskCreate) OnConflict(opts ...sql.ConflictOption) *EditableFileTaskUpsertOne {
	_c.conflict = opts
	return &EditableFileTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EditableFileTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EditableFileTaskCreate) OnConflictColumns(columns ...string) *EditableFileTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EditableFileTaskUpsertOne{
		create: _c,
	}
}

type (
	// EditableFileTaskUpsertOne is the builder for "upsert"-ing
	//  one EditableFileTask node.
	EditableFileTaskUpsertOne struct {
		create *EditableFileTaskCreate
	}

	// EditableFileTaskUpsert is the "OnConflict" setter.
	EditableFileTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EditableFileTaskUpsert) SetUpdatedAt(v time.Time) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateUpdatedAt() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EditableFileTaskUpsert) SetDeletedAt(v time.Time) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateDeletedAt() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EditableFileTaskUpsert) ClearDeletedAt() *EditableFileTaskUpsert {
	u.SetNull(editablefiletask.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *EditableFileTaskUpsert) SetUserID(v int64) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateUserID() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *EditableFileTaskUpsert) AddUserID(v int64) *EditableFileTaskUpsert {
	u.Add(editablefiletask.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *EditableFileTaskUpsert) SetGroupID(v int64) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateGroupID() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *EditableFileTaskUpsert) AddGroupID(v int64) *EditableFileTaskUpsert {
	u.Add(editablefiletask.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EditableFileTaskUpsert) ClearGroupID() *EditableFileTaskUpsert {
	u.SetNull(editablefiletask.FieldGroupID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *EditableFileTaskUpsert) SetAPIKeyID(v int64) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateAPIKeyID() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *EditableFileTaskUpsert) AddAPIKeyID(v int64) *EditableFileTaskUpsert {
	u.Add(editablefiletask.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *EditableFileTaskUpsert) ClearAPIKeyID() *EditableFileTaskUpsert {
	u.SetNull(editablefiletask.FieldAPIKeyID)
	return u
}

// SetImageConversationID sets the "image_conversation_id" field.
func (u *EditableFileTaskUpsert) SetImageConversationID(v int64) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldImageConversationID, v)
	return u
}

// UpdateImageConversationID sets the "image_conversation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateImageConversationID() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldImageConversationID)
	return u
}

// AddImageConversationID adds v to the "image_conversation_id" field.
func (u *EditableFileTaskUpsert) AddImageConversationID(v int64) *EditableFileTaskUpsert {
	u.Add(editablefiletask.FieldImageConversationID, v)
	return u
}

// ClearImageConversationID clears the value of the "image_conversation_id" field.
func (u *EditableFileTaskUpsert) ClearImageConversationID() *EditableFileTaskUpsert {
	u.SetNull(editablefiletask.FieldImageConversationID)
	return u
}

// SetSourceGenerationID sets the "source_generation_id" field.
func (u *EditableFileTaskUpsert) SetSourceGenerationID(v int64) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldSourceGenerationID, v)
	return u
}

// UpdateSourceGenerationID sets the "source_generation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateSourceGenerationID() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldSourceGenerationID)
	return u
}

// AddSourceGenerationID adds v to the "source_generation_id" field.
func (u *EditableFileTaskUpsert) AddSourceGenerationID(v int64) *EditableFileTaskUpsert {
	u.Add(editablefiletask.FieldSourceGenerationID, v)
	return u
}

// ClearSourceGenerationID clears the value of the "source_generation_id" field.
func (u *EditableFileTaskUpsert) ClearSourceGenerationID() *EditableFileTaskUpsert {
	u.SetNull(editablefiletask.FieldSourceGenerationID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *EditableFileTaskUpsert) SetAccountID(v int64) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateAccountID() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *EditableFileTaskUpsert) AddAccountID(v int64) *EditableFileTaskUpsert {
	u.Add(editablefiletask.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *EditableFileTaskUpsert) ClearAccountID() *EditableFileTaskUpsert {
	u.SetNull(editablefiletask.FieldAccountID)
	return u
}

// SetKind sets the "kind" field.
func (u *EditableFileTaskUpsert) SetKind(v string) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateKind() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldKind)
	return u
}

// SetStatus sets the "status" field.
func (u *EditableFileTaskUpsert) SetStatus(v string) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateStatus() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldStatus)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *EditableFileTaskUpsert) SetPrompt(v string) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdatePrompt() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldPrompt)
	return u
}

// SetModel sets the "model" field.
func (u *EditableFileTaskUpsert) SetModel(v string) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateModel() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldModel)
	return u
}

// SetClientTaskID sets the "client_task_id" field.
func (u *EditableFileTaskUpsert) SetClientTaskID(v string) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldClientTaskID, v)
	return u
}

// UpdateClientTaskID sets the "client_task_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateClientTaskID() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldClientTaskID)
	return u
}

// SetChatgptConversationID sets the "chatgpt_conversation_id" field.
func (u *EditableFileTaskUpsert) SetChatgptConversationID(v string) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldChatgptConversationID, v)
	return u
}

// UpdateChatgptConversationID sets the "chatgpt_conversation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateChatgptConversationID() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldChatgptConversationID)
	return u
}

// SetCost sets the "cost" field.
func (u *EditableFileTaskUpsert) SetCost(v float64) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateCost() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *EditableFileTaskUpsert) AddCost(v float64) *EditableFileTaskUpsert {
	u.Add(editablefiletask.FieldCost, v)
	return u
}

// SetError sets the "error" field.
func (u *EditableFileTaskUpsert) SetError(v string) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateError() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *EditableFileTaskUpsert) ClearError() *EditableFileTaskUpsert {
	u.SetNull(editablefiletask.FieldError)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *EditableFileTaskUpsert) SetExpiresAt(v time.Time) *EditableFileTaskUpsert {
	u.Set(editablefiletask.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsert) UpdateExpiresAt() *EditableFileTaskUpsert {
	u.SetExcluded(editablefiletask.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *EditableFileTaskUpsert) ClearExpiresAt() *EditableFileTaskUpsert {
	u.SetNull(editablefiletask.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EditableFileTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EditableFileTaskUpsertOne) UpdateNewValues() *EditableFileTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(editablefiletask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EditableFileTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EditableFileTaskUpsertOne) Ignore() *EditableFileTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EditableFileTaskUpsertOne) DoNothing() *EditableFileTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EditableFileTaskCreate.OnConflict
// documentation for more info.
func (u *EditableFileTaskUpsertOne) Update(set func(*EditableFileTaskUpsert)) *EditableFileTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EditableFileTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EditableFileTaskUpsertOne) SetUpdatedAt(v time.Time) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateUpdatedAt() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EditableFileTaskUpsertOne) SetDeletedAt(v time.Time) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateDeletedAt() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EditableFileTaskUpsertOne) ClearDeletedAt() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EditableFileTaskUpsertOne) SetUserID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *EditableFileTaskUpsertOne) AddUserID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateUserID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EditableFileTaskUpsertOne) SetGroupID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *EditableFileTaskUpsertOne) AddGroupID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateGroupID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EditableFileTaskUpsertOne) ClearGroupID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearGroupID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *EditableFileTaskUpsertOne) SetAPIKeyID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *EditableFileTaskUpsertOne) AddAPIKeyID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateAPIKeyID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *EditableFileTaskUpsertOne) ClearAPIKeyID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetImageConversationID sets the "image_conversation_id" field.
func (u *EditableFileTaskUpsertOne) SetImageConversationID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetImageConversationID(v)
	})
}

// AddImageConversationID adds v to the "image_conversation_id" field.
func (u *EditableFileTaskUpsertOne) AddImageConversationID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddImageConversationID(v)
	})
}

// UpdateImageConversationID sets the "image_conversation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateImageConversationID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateImageConversationID()
	})
}

// ClearImageConversationID clears the value of the "image_conversation_id" field.
func (u *EditableFileTaskUpsertOne) ClearImageConversationID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearImageConversationID()
	})
}

// SetSourceGenerationID sets the "source_generation_id" field.
func (u *EditableFileTaskUpsertOne) SetSourceGenerationID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetSourceGenerationID(v)
	})
}

// AddSourceGenerationID adds v to the "source_generation_id" field.
func (u *EditableFileTaskUpsertOne) AddSourceGenerationID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddSourceGenerationID(v)
	})
}

// UpdateSourceGenerationID sets the "source_generation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateSourceGenerationID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateSourceGenerationID()
	})
}

// ClearSourceGenerationID clears the value of the "source_generation_id" field.
func (u *EditableFileTaskUpsertOne) ClearSourceGenerationID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearSourceGenerationID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *EditableFileTaskUpsertOne) SetAccountID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *EditableFileTaskUpsertOne) AddAccountID(v int64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateAccountID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *EditableFileTaskUpsertOne) ClearAccountID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearAccountID()
	})
}

// SetKind sets the "kind" field.
func (u *EditableFileTaskUpsertOne) SetKind(v string) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateKind() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateKind()
	})
}

// SetStatus sets the "status" field.
func (u *EditableFileTaskUpsertOne) SetStatus(v string) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateStatus() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetPrompt sets the "prompt" field.
func (u *EditableFileTaskUpsertOne) SetPrompt(v string) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdatePrompt() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdatePrompt()
	})
}

// SetModel sets the "model" field.
func (u *EditableFileTaskUpsertOne) SetModel(v string) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateModel() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateModel()
	})
}

// SetClientTaskID sets the "client_task_id" field.
func (u *EditableFileTaskUpsertOne) SetClientTaskID(v string) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetClientTaskID(v)
	})
}

// UpdateClientTaskID sets the "client_task_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateClientTaskID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateClientTaskID()
	})
}

// SetChatgptConversationID sets the "chatgpt_conversation_id" field.
func (u *EditableFileTaskUpsertOne) SetChatgptConversationID(v string) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetChatgptConversationID(v)
	})
}

// UpdateChatgptConversationID sets the "chatgpt_conversation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateChatgptConversationID() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateChatgptConversationID()
	})
}

// SetCost sets the "cost" field.
func (u *EditableFileTaskUpsertOne) SetCost(v float64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *EditableFileTaskUpsertOne) AddCost(v float64) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateCost() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateCost()
	})
}

// SetError sets the "error" field.
func (u *EditableFileTaskUpsertOne) SetError(v string) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateError() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *EditableFileTaskUpsertOne) ClearError() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearError()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EditableFileTaskUpsertOne) SetExpiresAt(v time.Time) *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsertOne) UpdateExpiresAt() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *EditableFileTaskUpsertOne) ClearExpiresAt() *EditableFileTaskUpsertOne {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *EditableFileTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EditableFileTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EditableFileTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EditableFileTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EditableFileTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EditableFileTaskCreateBulk is the builder for creating many EditableFileTask entities in bulk.
type EditableFileTaskCreateBulk struct {
	config
	err      error
	builders []*EditableFileTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the EditableFileTask entities in the database.
func (_c *EditableFileTaskCreateBulk) Save(ctx context.Context) ([]*EditableFileTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EditableFileTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EditableFileTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EditableFileTaskCreateBulk) SaveX(ctx context.Context) []*EditableFileTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EditableFileTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EditableFileTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EditableFileTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EditableFileTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EditableFileTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *EditableFileTaskUpsertBulk {
	_c.conflict = opts
	return &EditableFileTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EditableFileTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EditableFileTaskCreateBulk) OnConflictColumns(columns ...string) *EditableFileTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EditableFileTaskUpsertBulk{
		create: _c,
	}
}

// EditableFileTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of EditableFileTask nodes.
type EditableFileTaskUpsertBulk struct {
	create *EditableFileTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EditableFileTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EditableFileTaskUpsertBulk) UpdateNewValues() *EditableFileTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(editablefiletask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EditableFileTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EditableFileTaskUpsertBulk) Ignore() *EditableFileTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EditableFileTaskUpsertBulk) DoNothing() *EditableFileTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EditableFileTaskCreateBulk.OnConflict
// documentation for more info.
func (u *EditableFileTaskUpsertBulk) Update(set func(*EditableFileTaskUpsert)) *EditableFileTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EditableFileTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EditableFileTaskUpsertBulk) SetUpdatedAt(v time.Time) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateUpdatedAt() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EditableFileTaskUpsertBulk) SetDeletedAt(v time.Time) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateDeletedAt() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EditableFileTaskUpsertBulk) ClearDeletedAt() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *EditableFileTaskUpsertBulk) SetUserID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *EditableFileTaskUpsertBulk) AddUserID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateUserID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EditableFileTaskUpsertBulk) SetGroupID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *EditableFileTaskUpsertBulk) AddGroupID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateGroupID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *EditableFileTaskUpsertBulk) ClearGroupID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearGroupID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *EditableFileTaskUpsertBulk) SetAPIKeyID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *EditableFileTaskUpsertBulk) AddAPIKeyID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateAPIKeyID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *EditableFileTaskUpsertBulk) ClearAPIKeyID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetImageConversationID sets the "image_conversation_id" field.
func (u *EditableFileTaskUpsertBulk) SetImageConversationID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetImageConversationID(v)
	})
}

// AddImageConversationID adds v to the "image_conversation_id" field.
func (u *EditableFileTaskUpsertBulk) AddImageConversationID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddImageConversationID(v)
	})
}

// UpdateImageConversationID sets the "image_conversation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateImageConversationID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateImageConversationID()
	})
}

// ClearImageConversationID clears the value of the "image_conversation_id" field.
func (u *EditableFileTaskUpsertBulk) ClearImageConversationID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearImageConversationID()
	})
}

// SetSourceGenerationID sets the "source_generation_id" field.
func (u *EditableFileTaskUpsertBulk) SetSourceGenerationID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetSourceGenerationID(v)
	})
}

// AddSourceGenerationID adds v to the "source_generation_id" field.
func (u *EditableFileTaskUpsertBulk) AddSourceGenerationID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddSourceGenerationID(v)
	})
}

// UpdateSourceGenerationID sets the "source_generation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateSourceGenerationID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateSourceGenerationID()
	})
}

// ClearSourceGenerationID clears the value of the "source_generation_id" field.
func (u *EditableFileTaskUpsertBulk) ClearSourceGenerationID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearSourceGenerationID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *EditableFileTaskUpsertBulk) SetAccountID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *EditableFileTaskUpsertBulk) AddAccountID(v int64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateAccountID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *EditableFileTaskUpsertBulk) ClearAccountID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearAccountID()
	})
}

// SetKind sets the "kind" field.
func (u *EditableFileTaskUpsertBulk) SetKind(v string) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateKind() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateKind()
	})
}

// SetStatus sets the "status" field.
func (u *EditableFileTaskUpsertBulk) SetStatus(v string) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateStatus() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetPrompt sets the "prompt" field.
func (u *EditableFileTaskUpsertBulk) SetPrompt(v string) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdatePrompt() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdatePrompt()
	})
}

// SetModel sets the "model" field.
func (u *EditableFileTaskUpsertBulk) SetModel(v string) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateModel() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateModel()
	})
}

// SetClientTaskID sets the "client_task_id" field.
func (u *EditableFileTaskUpsertBulk) SetClientTaskID(v string) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetClientTaskID(v)
	})
}

// UpdateClientTaskID sets the "client_task_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateClientTaskID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateClientTaskID()
	})
}

// SetChatgptConversationID sets the "chatgpt_conversation_id" field.
func (u *EditableFileTaskUpsertBulk) SetChatgptConversationID(v string) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetChatgptConversationID(v)
	})
}

// UpdateChatgptConversationID sets the "chatgpt_conversation_id" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateChatgptConversationID() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateChatgptConversationID()
	})
}

// SetCost sets the "cost" field.
func (u *EditableFileTaskUpsertBulk) SetCost(v float64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *EditableFileTaskUpsertBulk) AddCost(v float64) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateCost() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateCost()
	})
}

// SetError sets the "error" field.
func (u *EditableFileTaskUpsertBulk) SetError(v string) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateError() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *EditableFileTaskUpsertBulk) ClearError() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearError()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *EditableFileTaskUpsertBulk) SetExpiresAt(v time.Time) *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *EditableFileTaskUpsertBulk) UpdateExpiresAt() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *EditableFileTaskUpsertBulk) ClearExpiresAt() *EditableFileTaskUpsertBulk {
	return u.Update(func(s *EditableFileTaskUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *EditableFileTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EditableFileTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EditableFileTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EditableFileTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
