// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/editablefiletask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EditableFileTaskUpdate is the builder for updating EditableFileTask entities.
type EditableFileTaskUpdate struct {
	config
	hooks    []Hook
	mutation *EditableFileTaskMutation
}

// Where appends a list predicates to the EditableFileTaskUpdate builder.
func (_u *EditableFileTaskUpdate) Where(ps ...predicate.EditableFileTask) *EditableFileTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EditableFileTaskUpdate) SetUpdatedAt(v time.Time) *EditableFileTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EditableFileTaskUpdate) SetDeletedAt(v time.Time) *EditableFileTaskUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableDeletedAt(v *time.Time) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EditableFileTaskUpdate) ClearDeletedAt() *EditableFileTaskUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EditableFileTaskUpdate) SetUserID(v int64) *EditableFileTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableUserID(v *int64) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *EditableFileTaskUpdate) AddUserID(v int64) *EditableFileTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EditableFileTaskUpdate) SetGroupID(v int64) *EditableFileTaskUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableGroupID(v *int64) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *EditableFileTaskUpdate) AddGroupID(v int64) *EditableFileTaskUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *EditableFileTaskUpdate) ClearGroupID() *EditableFileTaskUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *EditableFileTaskUpdate) SetAPIKeyID(v int64) *EditableFileTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableAPIKeyID(v *int64) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *EditableFileTaskUpdate) AddAPIKeyID(v int64) *EditableFileTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *EditableFileTaskUpdate) ClearAPIKeyID() *EditableFileTaskUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetImageConversationID sets the "image_conversation_id" field.
func (_u *EditableFileTaskUpdate) SetImageConversationID(v int64) *EditableFileTaskUpdate {
	_u.mutation.ResetImageConversationID()
	_u.mutation.SetImageConversationID(v)
	return _u
}

// SetNillableImageConversationID sets the "image_conversation_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableImageConversationID(v *int64) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetImageConversationID(*v)
	}
	return _u
}

// AddImageConversationID adds value to the "image_conversation_id" field.
func (_u *EditableFileTaskUpdate) AddImageConversationID(v int64) *EditableFileTaskUpdate {
	_u.mutation.AddImageConversationID(v)
	return _u
}

// ClearImageConversationID clears the value of the "image_conversation_id" field.
func (_u *EditableFileTaskUpdate) ClearImageConversationID() *EditableFileTaskUpdate {
	_u.mutation.ClearImageConversationID()
	return _u
}

// SetSourceGenerationID sets the "source_generation_id" field.
func (_u *EditableFileTaskUpdate) SetSourceGenerationID(v int64) *EditableFileTaskUpdate {
	_u.mutation.ResetSourceGenerationID()
	_u.mutation.SetSourceGenerationID(v)
	return _u
}

// SetNillableSourceGenerationID sets the "source_generation_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableSourceGenerationID(v *int64) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetSourceGenerationID(*v)
	}
	return _u
}

// AddSourceGenerationID adds value to the "source_generation_id" field.
func (_u *EditableFileTaskUpdate) AddSourceGenerationID(v int64) *EditableFileTaskUpdate {
	_u.mutation.AddSourceGenerationID(v)
	return _u
}

// ClearSourceGenerationID clears the value of the "source_generation_id" field.
func (_u *EditableFileTaskUpdate) ClearSourceGenerationID() *EditableFileTaskUpdate {
	_u.mutation.ClearSourceGenerationID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *EditableFileTaskUpdate) SetAccountID(v int64) *EditableFileTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableAccountID(v *int64) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *EditableFileTaskUpdate) AddAccountID(v int64) *EditableFileTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *EditableFileTaskUpdate) ClearAccountID() *EditableFileTaskUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *EditableFileTaskUpdate) SetKind(v string) *EditableFileTaskUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableKind(v *string) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EditableFileTaskUpdate) SetStatus(v string) *EditableFileTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableStatus(v *string) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *EditableFileTaskUpdate) SetPrompt(v string) *EditableFileTaskUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillablePrompt(v *string) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *EditableFileTaskUpdate) SetModel(v string) *EditableFileTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableModel(v *string) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetClientTaskID sets the "client_task_id" field.
func (_u *EditableFileTaskUpdate) SetClientTaskID(v string) *EditableFileTaskUpdate {
	_u.mutation.SetClientTaskID(v)
	return _u
}

// SetNillableClientTaskID sets the "client_task_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableClientTaskID(v *string) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetClientTaskID(*v)
	}
	return _u
}

// SetChatgptConversationID sets the "chatgpt_conversation_id" field.
func (_u *EditableFileTaskUpdate) SetChatgptConversationID(v string) *EditableFileTaskUpdate {
	_u.mutation.SetChatgptConversationID(v)
	return _u
}

// SetNillableChatgptConversationID sets the "chatgpt_conversation_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableChatgptConversationID(v *string) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetChatgptConversationID(*v)
	}
	return _u
}

// SetCost sets the "cost" field.
func (_u *EditableFileTaskUpdate) SetCost(v float64) *EditableFileTaskUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableCost(v *float64) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *EditableFileTaskUpdate) AddCost(v float64) *EditableFileTaskUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetError sets the "error" field.
func (_u *EditableFileTaskUpdate) SetError(v string) *EditableFileTaskUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableError(v *string) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *EditableFileTaskUpdate) ClearError() *EditableFileTaskUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EditableFileTaskUpdate) SetExpiresAt(v time.Time) *EditableFileTaskUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EditableFileTaskUpdate) SetNillableExpiresAt(v *time.Time) *EditableFileTaskUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *EditableFileTaskUpdate) ClearExpiresAt() *EditableFileTaskUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the EditableFileTaskMutation object of the builder.
func (_u *EditableFileTaskUpdate) Mutation() *EditableFileTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EditableFileTaskUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EditableFileTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EditableFileTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EditableFileTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EditableFileTaskUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if editablefiletask.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized editablefiletask.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := editablefiletask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EditableFileTaskUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := editablefiletask.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := editablefiletask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := editablefiletask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientTaskID(); ok {
		if err := editablefiletask.ClientTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "client_task_id", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.client_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatgptConversationID(); ok {
		if err := editablefiletask.ChatgptConversationIDValidator(v); err != nil {
			return &ValidationError{Name: "chatgpt_conversation_id", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.chatgpt_conversation_id": %w`, err)}
		}
	}
	return nil
}

func (_u *EditableFileTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(editablefiletask.Table, editablefiletask.Columns, sqlgraph.NewFieldSpec(editablefiletask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(editablefiletask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(editablefiletask.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(editablefiletask.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(editablefiletask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(editablefiletask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(editablefiletask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(editablefiletask.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(editablefiletask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(editablefiletask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(editablefiletask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(editablefiletask.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImageConversationID(); ok {
		_spec.SetField(editablefiletask.FieldImageConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageConversationID(); ok {
		_spec.AddField(editablefiletask.FieldImageConversationID, field.TypeInt64, value)
	}
	if _u.mutation.ImageConversationIDCleared() {
		_spec.ClearField(editablefiletask.FieldImageConversationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceGenerationID(); ok {
		_spec.SetField(editablefiletask.FieldSourceGenerationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceGenerationID(); ok {
		_spec.AddField(editablefiletask.FieldSourceGenerationID, field.TypeInt64, value)
	}
	if _u.mutation.SourceGenerationIDCleared() {
		_spec.ClearField(editablefiletask.FieldSourceGenerationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(editablefiletask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(editablefiletask.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(editablefiletask.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(editablefiletask.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(editablefiletask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(editablefiletask.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(editablefiletask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientTaskID(); ok {
		_spec.SetField(editablefiletask.FieldClientTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChatgptConversationID(); ok {
		_spec.SetField(editablefiletask.FieldChatgptConversationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(editablefiletask.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(editablefiletask.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(editablefiletask.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(editablefiletask.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(editablefiletask.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(editablefiletask.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{editablefiletask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EditableFileTaskUpdateOne is the builder for updating a single EditableFileTask entity.
type EditableFileTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EditableFileTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EditableFileTaskUpdateOne) SetUpdatedAt(v time.Time) *EditableFileTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EditableFileTaskUpdateOne) SetDeletedAt(v time.Time) *EditableFileTaskUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableDeletedAt(v *time.Time) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EditableFileTaskUpdateOne) ClearDeletedAt() *EditableFileTaskUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EditableFileTaskUpdateOne) SetUserID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableUserID(v *int64) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *EditableFileTaskUpdateOne) AddUserID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EditableFileTaskUpdateOne) SetGroupID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableGroupID(v *int64) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *EditableFileTaskUpdateOne) AddGroupID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *EditableFileTaskUpdateOne) ClearGroupID() *EditableFileTaskUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *EditableFileTaskUpdateOne) SetAPIKeyID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableAPIKeyID(v *int64) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *EditableFileTaskUpdateOne) AddAPIKeyID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *EditableFileTaskUpdateOne) ClearAPIKeyID() *EditableFileTaskUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetImageConversationID sets the "image_conversation_id" field.
func (_u *EditableFileTaskUpdateOne) SetImageConversationID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.ResetImageConversationID()
	_u.mutation.SetImageConversationID(v)
	return _u
}

// SetNillableImageConversationID sets the "image_conversation_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableImageConversationID(v *int64) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetImageConversationID(*v)
	}
	return _u
}

// AddImageConversationID adds value to the "image_conversation_id" field.
func (_u *EditableFileTaskUpdateOne) AddImageConversationID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.AddImageConversationID(v)
	return _u
}

// ClearImageConversationID clears the value of the "image_conversation_id" field.
func (_u *EditableFileTaskUpdateOne) ClearImageConversationID() *EditableFileTaskUpdateOne {
	_u.mutation.ClearImageConversationID()
	return _u
}

// SetSourceGenerationID sets the "source_generation_id" field.
func (_u *EditableFileTaskUpdateOne) SetSourceGenerationID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.ResetSourceGenerationID()
	_u.mutation.SetSourceGenerationID(v)
	return _u
}

// SetNillableSourceGenerationID sets the "source_generation_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableSourceGenerationID(v *int64) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetSourceGenerationID(*v)
	}
	return _u
}

// AddSourceGenerationID adds value to the "source_generation_id" field.
func (_u *EditableFileTaskUpdateOne) AddSourceGenerationID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.AddSourceGenerationID(v)
	return _u
}

// ClearSourceGenerationID clears the value of the "source_generation_id" field.
func (_u *EditableFileTaskUpdateOne) ClearSourceGenerationID() *EditableFileTaskUpdateOne {
	_u.mutation.ClearSourceGenerationID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *EditableFileTaskUpdateOne) SetAccountID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableAccountID(v *int64) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *EditableFileTaskUpdateOne) AddAccountID(v int64) *EditableFileTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *EditableFileTaskUpdateOne) ClearAccountID() *EditableFileTaskUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *EditableFileTaskUpdateOne) SetKind(v string) *EditableFileTaskUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableKind(v *string) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EditableFileTaskUpdateOne) SetStatus(v string) *EditableFileTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableStatus(v *string) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *EditableFileTaskUpdateOne) SetPrompt(v string) *EditableFileTaskUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillablePrompt(v *string) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *EditableFileTaskUpdateOne) SetModel(v string) *EditableFileTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableModel(v *string) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetClientTaskID sets the "client_task_id" field.
func (_u *EditableFileTaskUpdateOne) SetClientTaskID(v string) *EditableFileTaskUpdateOne {
	_u.mutation.SetClientTaskID(v)
	return _u
}

// SetNillableClientTaskID sets the "client_task_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableClientTaskID(v *string) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetClientTaskID(*v)
	}
	return _u
}

// SetChatgptConversationID sets the "chatgpt_conversation_id" field.
func (_u *EditableFileTaskUpdateOne) SetChatgptConversationID(v string) *EditableFileTaskUpdateOne {
	_u.mutation.SetChatgptConversationID(v)
	return _u
}

// SetNillableChatgptConversationID sets the "chatgpt_conversation_id" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableChatgptConversationID(v *string) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetChatgptConversationID(*v)
	}
	return _u
}

// SetCost sets the "cost" field.
func (_u *EditableFileTaskUpdateOne) SetCost(v float64) *EditableFileTaskUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableCost(v *float64) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *EditableFileTaskUpdateOne) AddCost(v float64) *EditableFileTaskUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetError sets the "error" field.
func (_u *EditableFileTaskUpdateOne) SetError(v string) *EditableFileTaskUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableError(v *string) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *EditableFileTaskUpdateOne) ClearError() *EditableFileTaskUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EditableFileTaskUpdateOne) SetExpiresAt(v time.Time) *EditableFileTaskUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EditableFileTaskUpdateOne) SetNillableExpiresAt(v *time.Time) *EditableFileTaskUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *EditableFileTaskUpdateOne) ClearExpiresAt() *EditableFileTaskUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the EditableFileTaskMutation object of the builder.
func (_u *EditableFileTaskUpdateOne) Mutation() *EditableFileTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the EditableFileTaskUpdate builder.
func (_u *EditableFileTaskUpdateOne) Where(ps ...predicate.EditableFileTask) *EditableFileTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EditableFileTaskUpdateOne) Select(field string, fields ...string) *EditableFileTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EditableFileTask entity.
func (_u *EditableFileTaskUpdateOne) Save(ctx context.Context) (*EditableFileTask, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EditableFileTaskUpdateOne) SaveX(ctx context.Context) *EditableFileTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EditableFileTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EditableFileTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EditableFileTaskUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if editablefiletask.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized editablefiletask.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := editablefiletask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EditableFileTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := editablefiletask.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := editablefiletask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := editablefiletask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientTaskID(); ok {
		if err := editablefiletask.ClientTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "client_task_id", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.client_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatgptConversationID(); ok {
		if err := editablefiletask.ChatgptConversationIDValidator(v); err != nil {
			return &ValidationError{Name: "chatgpt_conversation_id", err: fmt.Errorf(`ent: validator failed for field "EditableFileTask.chatgpt_conversation_id": %w`, err)}
		}
	}
	return nil
}

func (_u *EditableFileTaskUpdateOne) sqlSave(ctx context.Context) (_node *EditableFileTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(editablefiletask.Table, editablefiletask.Columns, sqlgraph.NewFieldSpec(editablefiletask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EditableFileTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, editablefiletask.FieldID)
		for _, f := range fields {
			if !editablefiletask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != editablefiletask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(editablefiletask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(editablefiletask.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(editablefiletask.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(editablefiletask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(editablefiletask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(editablefiletask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(editablefiletask.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(editablefiletask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(editablefiletask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(editablefiletask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(editablefiletask.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ImageConversationID(); ok {
		_spec.SetField(editablefiletask.FieldImageConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedImageConversationID(); ok {
		_spec.AddField(editablefiletask.FieldImageConversationID, field.TypeInt64, value)
	}
	if _u.mutation.ImageConversationIDCleared() {
		_spec.ClearField(editablefiletask.FieldImageConversationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceGenerationID(); ok {
		_spec.SetField(editablefiletask.FieldSourceGenerationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceGenerationID(); ok {
		_spec.AddField(editablefiletask.FieldSourceGenerationID, field.TypeInt64, value)
	}
	if _u.mutation.SourceGenerationIDCleared() {
		_spec.ClearField(editablefiletask.FieldSourceGenerationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(editablefiletask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(editablefiletask.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(editablefiletask.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(editablefiletask.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(editablefiletask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(editablefiletask.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(editablefiletask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientTaskID(); ok {
		_spec.SetField(editablefiletask.FieldClientTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChatgptConversationID(); ok {
		_spec.SetField(editablefiletask.FieldChatgptConversationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(editablefiletask.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(editablefiletask.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(editablefiletask.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(editablefiletask.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(editablefiletask.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(editablefiletask.FieldExpiresAt, field.TypeTime)
	}
	_node = &EditableFileTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{editablefiletask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
