// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/editablefileartifact"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EditableFileArtifactUpdate is the builder for updating EditableFileArtifact entities.
type EditableFileArtifactUpdate struct {
	config
	hooks    []Hook
	mutation *EditableFileArtifactMutation
}

// Where appends a list predicates to the EditableFileArtifactUpdate builder.
func (_u *EditableFileArtifactUpdate) Where(ps ...predicate.EditableFileArtifact) *EditableFileArtifactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EditableFileArtifactUpdate) SetUpdatedAt(v time.Time) *EditableFileArtifactUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EditableFileArtifactUpdate) SetDeletedAt(v time.Time) *EditableFileArtifactUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableDeletedAt(v *time.Time) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EditableFileArtifactUpdate) ClearDeletedAt() *EditableFileArtifactUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *EditableFileArtifactUpdate) SetTaskID(v int64) *EditableFileArtifactUpdate {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableTaskID(v *int64) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *EditableFileArtifactUpdate) AddTaskID(v int64) *EditableFileArtifactUpdate {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EditableFileArtifactUpdate) SetUserID(v int64) *EditableFileArtifactUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableUserID(v *int64) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *EditableFileArtifactUpdate) AddUserID(v int64) *EditableFileArtifactUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *EditableFileArtifactUpdate) SetKind(v string) *EditableFileArtifactUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableKind(v *string) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *EditableFileArtifactUpdate) SetFileName(v string) *EditableFileArtifactUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableFileName(v *string) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *EditableFileArtifactUpdate) SetMimeType(v string) *EditableFileArtifactUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableMimeType(v *string) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *EditableFileArtifactUpdate) SetSizeBytes(v int64) *EditableFileArtifactUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableSizeBytes(v *int64) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *EditableFileArtifactUpdate) AddSizeBytes(v int64) *EditableFileArtifactUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *EditableFileArtifactUpdate) SetStorageKey(v string) *EditableFileArtifactUpdate {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableStorageKey(v *string) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetSourcePointer sets the "source_pointer" field.
func (_u *EditableFileArtifactUpdate) SetSourcePointer(v string) *EditableFileArtifactUpdate {
	_u.mutation.SetSourcePointer(v)
	return _u
}

// SetNillableSourcePointer sets the "source_pointer" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableSourcePointer(v *string) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetSourcePointer(*v)
	}
	return _u
}

// ClearSourcePointer clears the value of the "source_pointer" field.
func (_u *EditableFileArtifactUpdate) ClearSourcePointer() *EditableFileArtifactUpdate {
	_u.mutation.ClearSourcePointer()
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *EditableFileArtifactUpdate) SetSha256(v string) *EditableFileArtifactUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *EditableFileArtifactUpdate) SetNillableSha256(v *string) *EditableFileArtifactUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// Mutation returns the EditableFileArtifactMutation object of the builder.
func (_u *EditableFileArtifactUpdate) Mutation() *EditableFileArtifactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EditableFileArtifactUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EditableFileArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EditableFileArtifactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EditableFileArtifactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EditableFileArtifactUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if editablefileartifact.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized editablefileartifact.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := editablefileartifact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EditableFileArtifactUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := editablefileartifact.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EditableFileArtifact.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := editablefileartifact.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "EditableFileArtifact.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := editablefileartifact.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "EditableFileArtifact.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := editablefileartifact.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "EditableFileArtifact.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *EditableFileArtifactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(editablefileartifact.Table, editablefileartifact.Columns, sqlgraph.NewFieldSpec(editablefileartifact.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(editablefileartifact.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(editablefileartifact.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(editablefileartifact.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(editablefileartifact.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(editablefileartifact.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(editablefileartifact.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(editablefileartifact.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(editablefileartifact.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(editablefileartifact.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(editablefileartifact.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(editablefileartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(editablefileartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(editablefileartifact.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourcePointer(); ok {
		_spec.SetField(editablefileartifact.FieldSourcePointer, field.TypeString, value)
	}
	if _u.mutation.SourcePointerCleared() {
		_spec.ClearField(editablefileartifact.FieldSourcePointer, field.TypeString)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(editablefileartifact.FieldSha256, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{editablefileartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EditableFileArtifactUpdateOne is the builder for updating a single EditableFileArtifact entity.
type EditableFileArtifactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EditableFileArtifactMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EditableFileArtifactUpdateOne) SetUpdatedAt(v time.Time) *EditableFileArtifactUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EditableFileArtifactUpdateOne) SetDeletedAt(v time.Time) *EditableFileArtifactUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableDeletedAt(v *time.Time) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EditableFileArtifactUpdateOne) ClearDeletedAt() *EditableFileArtifactUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *EditableFileArtifactUpdateOne) SetTaskID(v int64) *EditableFileArtifactUpdateOne {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableTaskID(v *int64) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *EditableFileArtifactUpdateOne) AddTaskID(v int64) *EditableFileArtifactUpdateOne {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EditableFileArtifactUpdateOne) SetUserID(v int64) *EditableFileArtifactUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableUserID(v *int64) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *EditableFileArtifactUpdateOne) AddUserID(v int64) *EditableFileArtifactUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *EditableFileArtifactUpdateOne) SetKind(v string) *EditableFileArtifactUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableKind(v *string) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *EditableFileArtifactUpdateOne) SetFileName(v string) *EditableFileArtifactUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableFileName(v *string) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *EditableFileArtifactUpdateOne) SetMimeType(v string) *EditableFileArtifactUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableMimeType(v *string) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *EditableFileArtifactUpdateOne) SetSizeBytes(v int64) *EditableFileArtifactUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableSizeBytes(v *int64) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *EditableFileArtifactUpdateOne) AddSizeBytes(v int64) *EditableFileArtifactUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *EditableFileArtifactUpdateOne) SetStorageKey(v string) *EditableFileArtifactUpdateOne {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableStorageKey(v *string) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetSourcePointer sets the "source_pointer" field.
func (_u *EditableFileArtifactUpdateOne) SetSourcePointer(v string) *EditableFileArtifactUpdateOne {
	_u.mutation.SetSourcePointer(v)
	return _u
}

// SetNillableSourcePointer sets the "source_pointer" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableSourcePointer(v *string) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetSourcePointer(*v)
	}
	return _u
}

// ClearSourcePointer clears the value of the "source_pointer" field.
func (_u *EditableFileArtifactUpdateOne) ClearSourcePointer() *EditableFileArtifactUpdateOne {
	_u.mutation.ClearSourcePointer()
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *EditableFileArtifactUpdateOne) SetSha256(v string) *EditableFileArtifactUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *EditableFileArtifactUpdateOne) SetNillableSha256(v *string) *EditableFileArtifactUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// Mutation returns the EditableFileArtifactMutation object of the builder.
func (_u *EditableFileArtifactUpdateOne) Mutation() *EditableFileArtifactMutation {
	return _u.mutation
}

// Where appends a list predicates to the EditableFileArtifactUpdate builder.
func (_u *EditableFileArtifactUpdateOne) Where(ps ...predicate.EditableFileArtifact) *EditableFileArtifactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EditableFileArtifactUpdateOne) Select(field string, fields ...string) *EditableFileArtifactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EditableFileArtifact entity.
func (_u *EditableFileArtifactUpdateOne) Save(ctx context.Context) (*EditableFileArtifact, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EditableFileArtifactUpdateOne) SaveX(ctx context.Context) *EditableFileArtifact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EditableFileArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EditableFileArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EditableFileArtifactUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if editablefileartifact.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized editablefileartifact.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := editablefileartifact.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EditableFileArtifactUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := editablefileartifact.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EditableFileArtifact.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := editablefileartifact.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "EditableFileArtifact.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := editablefileartifact.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "EditableFileArtifact.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := editablefileartifact.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "EditableFileArtifact.sha256": %w`, err)}
		}
	}
	return nil
}

func (_u *EditableFileArtifactUpdateOne) sqlSave(ctx context.Context) (_node *EditableFileArtifact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(editablefileartifact.Table, editablefileartifact.Columns, sqlgraph.NewFieldSpec(editablefileartifact.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EditableFileArtifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, editablefileartifact.FieldID)
		for _, f := range fields {
			if !editablefileartifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != editablefileartifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(editablefileartifact.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(editablefileartifact.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(editablefileartifact.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(editablefileartifact.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(editablefileartifact.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(editablefileartifact.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(editablefileartifact.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(editablefileartifact.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(editablefileartifact.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(editablefileartifact.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(editablefileartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(editablefileartifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(editablefileartifact.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourcePointer(); ok {
		_spec.SetField(editablefileartifact.FieldSourcePointer, field.TypeString, value)
	}
	if _u.mutation.SourcePointerCleared() {
		_spec.ClearField(editablefileartifact.FieldSourcePointer, field.TypeString)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(editablefileartifact.FieldSha256, field.TypeString, value)
	}
	_node = &EditableFileArtifact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{editablefileartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
