// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/editablefileartifact"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EditableFileArtifactDelete is the builder for deleting a EditableFileArtifact entity.
type EditableFileArtifactDelete struct {
	config
	hooks    []Hook
	mutation *EditableFileArtifactMutation
}

// Where appends a list predicates to the EditableFileArtifactDelete builder.
func (_d *EditableFileArtifactDelete) Where(ps ...predicate.EditableFileArtifact) *EditableFileArtifactDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EditableFileArtifactDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EditableFileArtifactDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EditableFileArtifactDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(editablefileartifact.Table, sqlgraph.NewFieldSpec(editablefileartifact.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EditableFileArtifactDeleteOne is the builder for deleting a single EditableFileArtifact entity.
type EditableFileArtifactDeleteOne struct {
	_d *EditableFileArtifactDelete
}

// Where appends a list predicates to the EditableFileArtifactDelete builder.
func (_d *EditableFileArtifactDeleteOne) Where(ps ...predicate.EditableFileArtifact) *EditableFileArtifactDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EditableFileArtifactDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{editablefileartifact.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EditableFileArtifactDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
