// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagegeneration"
)

// ImageGenerationCreate is the builder for creating a ImageGeneration entity.
type ImageGenerationCreate struct {
	config
	mutation *ImageGenerationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageGenerationCreate) SetCreatedAt(v time.Time) *ImageGenerationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableCreatedAt(v *time.Time) *ImageGenerationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImageGenerationCreate) SetUpdatedAt(v time.Time) *ImageGenerationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableUpdatedAt(v *time.Time) *ImageGenerationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ImageGenerationCreate) SetDeletedAt(v time.Time) *ImageGenerationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableDeletedAt(v *time.Time) *ImageGenerationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ImageGenerationCreate) SetUserID(v int64) *ImageGenerationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *ImageGenerationCreate) SetConversationID(v int64) *ImageGenerationCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ImageGenerationCreate) SetGroupID(v int64) *ImageGenerationCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *ImageGenerationCreate) SetPrompt(v string) *ImageGenerationCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *ImageGenerationCreate) SetModel(v string) *ImageGenerationCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableModel(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *ImageGenerationCreate) SetSize(v string) *ImageGenerationCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableSize(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetQuality sets the "quality" field.
func (_c *ImageGenerationCreate) SetQuality(v string) *ImageGenerationCreate {
	_c.mutation.SetQuality(v)
	return _c
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableQuality(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetQuality(*v)
	}
	return _c
}

// SetN sets the "n" field.
func (_c *ImageGenerationCreate) SetN(v int) *ImageGenerationCreate {
	_c.mutation.SetN(v)
	return _c
}

// SetNillableN sets the "n" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableN(v *int) *ImageGenerationCreate {
	if v != nil {
		_c.SetN(*v)
	}
	return _c
}

// SetImageCount sets the "image_count" field.
func (_c *ImageGenerationCreate) SetImageCount(v int) *ImageGenerationCreate {
	_c.mutation.SetImageCount(v)
	return _c
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableImageCount(v *int) *ImageGenerationCreate {
	if v != nil {
		_c.SetImageCount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ImageGenerationCreate) SetStatus(v string) *ImageGenerationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableStatus(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *ImageGenerationCreate) SetCost(v float64) *ImageGenerationCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableCost(v *float64) *ImageGenerationCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetStorageKeys sets the "storage_keys" field.
func (_c *ImageGenerationCreate) SetStorageKeys(v []string) *ImageGenerationCreate {
	_c.mutation.SetStorageKeys(v)
	return _c
}

// SetInputStorageKeys sets the "input_storage_keys" field.
func (_c *ImageGenerationCreate) SetInputStorageKeys(v []string) *ImageGenerationCreate {
	_c.mutation.SetInputStorageKeys(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *ImageGenerationCreate) SetWidth(v int) *ImageGenerationCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableWidth(v *int) *ImageGenerationCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *ImageGenerationCreate) SetHeight(v int) *ImageGenerationCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableHeight(v *int) *ImageGenerationCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *ImageGenerationCreate) SetError(v string) *ImageGenerationCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableError(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *ImageGenerationCreate) SetErrorCode(v string) *ImageGenerationCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableErrorCode(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// Mutation returns the ImageGenerationMutation object of the builder.
func (_c *ImageGenerationCreate) Mutation() *ImageGenerationMutation {
	return _c.mutation
}

// Save creates the ImageGeneration in the database.
func (_c *ImageGenerationCreate) Save(ctx context.Context) (*ImageGeneration, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageGenerationCreate) SaveX(ctx context.Context) *ImageGeneration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageGenerationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageGenerationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageGenerationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if imagegeneration.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized imagegeneration.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := imagegeneration.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if imagegeneration.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imagegeneration.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imagegeneration.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := imagegeneration.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := imagegeneration.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.Quality(); !ok {
		v := imagegeneration.DefaultQuality
		_c.mutation.SetQuality(v)
	}
	if _, ok := _c.mutation.N(); !ok {
		v := imagegeneration.DefaultN
		_c.mutation.SetN(v)
	}
	if _, ok := _c.mutation.ImageCount(); !ok {
		v := imagegeneration.DefaultImageCount
		_c.mutation.SetImageCount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := imagegeneration.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := imagegeneration.DefaultCost
		_c.mutation.SetCost(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageGenerationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageGeneration.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImageGeneration.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImageGeneration.user_id"`)}
	}
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "ImageGeneration.conversation_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ImageGeneration.group_id"`)}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "ImageGeneration.prompt"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ImageGeneration.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := imagegeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "ImageGeneration.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := imagegeneration.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quality(); !ok {
		return &ValidationError{Name: "quality", err: errors.New(`ent: missing required field "ImageGeneration.quality"`)}
	}
	if v, ok := _c.mutation.Quality(); ok {
		if err := imagegeneration.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.quality": %w`, err)}
		}
	}
	if _, ok := _c.mutation.N(); !ok {
		return &ValidationError{Name: "n", err: errors.New(`ent: missing required field "ImageGeneration.n"`)}
	}
	if _, ok := _c.mutation.ImageCount(); !ok {
		return &ValidationError{Name: "image_count", err: errors.New(`ent: missing required field "ImageGeneration.image_count"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ImageGeneration.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := imagegeneration.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "ImageGeneration.cost"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := imagegeneration.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.error_code": %w`, err)}
		}
	}
	return nil
}

func (_c *ImageGenerationCreate) sqlSave(ctx context.Context) (*ImageGeneration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageGenerationCreate) createSpec() (*ImageGeneration, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageGeneration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imagegeneration.Table, sqlgraph.NewFieldSpec(imagegeneration.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imagegeneration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imagegeneration.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(imagegeneration.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(imagegeneration.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(imagegeneration.FieldConversationID, field.TypeInt64, value)
		_node.ConversationID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(imagegeneration.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(imagegeneration.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(imagegeneration.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(imagegeneration.FieldSize, field.TypeString, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Quality(); ok {
		_spec.SetField(imagegeneration.FieldQuality, field.TypeString, value)
		_node.Quality = value
	}
	if value, ok := _c.mutation.N(); ok {
		_spec.SetField(imagegeneration.FieldN, field.TypeInt, value)
		_node.N = value
	}
	if value, ok := _c.mutation.ImageCount(); ok {
		_spec.SetField(imagegeneration.FieldImageCount, field.TypeInt, value)
		_node.ImageCount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(imagegeneration.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(imagegeneration.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.StorageKeys(); ok {
		_spec.SetField(imagegeneration.FieldStorageKeys, field.TypeJSON, value)
		_node.StorageKeys = value
	}
	if value, ok := _c.mutation.InputStorageKeys(); ok {
		_spec.SetField(imagegeneration.FieldInputStorageKeys, field.TypeJSON, value)
		_node.InputStorageKeys = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(imagegeneration.FieldWidth, field.TypeInt, value)
		_node.Width = &value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(imagegeneration.FieldHeight, field.TypeInt, value)
		_node.Height = &value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(imagegeneration.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(imagegeneration.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageGeneration.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageGenerationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageGenerationCreate) OnConflict(opts ...sql.ConflictOption) *ImageGenerationUpsertOne {
	_c.conflict = opts
	return &ImageGenerationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageGenerationCreate) OnConflictColumns(columns ...string) *ImageGenerationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageGenerationUpsertOne{
		create: _c,
	}
}

type (
	// ImageGenerationUpsertOne is the builder for "upsert"-ing
	//  one ImageGeneration node.
	ImageGenerationUpsertOne struct {
		create *ImageGenerationCreate
	}

	// ImageGenerationUpsert is the "OnConflict" setter.
	ImageGenerationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageGenerationUpsert) SetUpdatedAt(v time.Time) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateUpdatedAt() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageGenerationUpsert) SetDeletedAt(v time.Time) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateDeletedAt() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageGenerationUpsert) ClearDeletedAt() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImageGenerationUpsert) SetUserID(v int64) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateUserID() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ImageGenerationUpsert) AddUserID(v int64) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldUserID, v)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ImageGenerationUpsert) SetConversationID(v int64) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateConversationID() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldConversationID)
	return u
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ImageGenerationUpsert) AddConversationID(v int64) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldConversationID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ImageGenerationUpsert) SetGroupID(v int64) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateGroupID() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *ImageGenerationUpsert) AddGroupID(v int64) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldGroupID, v)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *ImageGenerationUpsert) SetPrompt(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdatePrompt() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldPrompt)
	return u
}

// SetModel sets the "model" field.
func (u *ImageGenerationUpsert) SetModel(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateModel() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldModel)
	return u
}

// SetSize sets the "size" field.
func (u *ImageGenerationUpsert) SetSize(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateSize() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldSize)
	return u
}

// SetQuality sets the "quality" field.
func (u *ImageGenerationUpsert) SetQuality(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldQuality, v)
	return u
}

// UpdateQuality sets the "quality" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateQuality() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldQuality)
	return u
}

// SetN sets the "n" field.
func (u *ImageGenerationUpsert) SetN(v int) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldN, v)
	return u
}

// UpdateN sets the "n" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateN() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldN)
	return u
}

// AddN adds v to the "n" field.
func (u *ImageGenerationUpsert) AddN(v int) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldN, v)
	return u
}

// SetImageCount sets the "image_count" field.
func (u *ImageGenerationUpsert) SetImageCount(v int) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldImageCount, v)
	return u
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateImageCount() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldImageCount)
	return u
}

// AddImageCount adds v to the "image_count" field.
func (u *ImageGenerationUpsert) AddImageCount(v int) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldImageCount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ImageGenerationUpsert) SetStatus(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateStatus() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldStatus)
	return u
}

// SetCost sets the "cost" field.
func (u *ImageGenerationUpsert) SetCost(v float64) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateCost() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *ImageGenerationUpsert) AddCost(v float64) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldCost, v)
	return u
}

// SetStorageKeys sets the "storage_keys" field.
func (u *ImageGenerationUpsert) SetStorageKeys(v []string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldStorageKeys, v)
	return u
}

// UpdateStorageKeys sets the "storage_keys" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateStorageKeys() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldStorageKeys)
	return u
}

// ClearStorageKeys clears the value of the "storage_keys" field.
func (u *ImageGenerationUpsert) ClearStorageKeys() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldStorageKeys)
	return u
}

// SetInputStorageKeys sets the "input_storage_keys" field.
func (u *ImageGenerationUpsert) SetInputStorageKeys(v []string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldInputStorageKeys, v)
	return u
}

// UpdateInputStorageKeys sets the "input_storage_keys" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateInputStorageKeys() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldInputStorageKeys)
	return u
}

// ClearInputStorageKeys clears the value of the "input_storage_keys" field.
func (u *ImageGenerationUpsert) ClearInputStorageKeys() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldInputStorageKeys)
	return u
}

// SetWidth sets the "width" field.
func (u *ImageGenerationUpsert) SetWidth(v int) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateWidth() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *ImageGenerationUpsert) AddWidth(v int) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldWidth, v)
	return u
}

// ClearWidth clears the value of the "width" field.
func (u *ImageGenerationUpsert) ClearWidth() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldWidth)
	return u
}

// SetHeight sets the "height" field.
func (u *ImageGenerationUpsert) SetHeight(v int) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateHeight() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *ImageGenerationUpsert) AddHeight(v int) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldHeight, v)
	return u
}

// ClearHeight clears the value of the "height" field.
func (u *ImageGenerationUpsert) ClearHeight() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldHeight)
	return u
}

// SetError sets the "error" field.
func (u *ImageGenerationUpsert) SetError(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateError() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *ImageGenerationUpsert) ClearError() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldError)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *ImageGenerationUpsert) SetErrorCode(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateErrorCode() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageGenerationUpsert) ClearErrorCode() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldErrorCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageGenerationUpsertOne) UpdateNewValues() *ImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imagegeneration.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageGenerationUpsertOne) Ignore() *ImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageGenerationUpsertOne) DoNothing() *ImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageGenerationCreate.OnConflict
// documentation for more info.
func (u *ImageGenerationUpsertOne) Update(set func(*ImageGenerationUpsert)) *ImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageGenerationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageGenerationUpsertOne) SetUpdatedAt(v time.Time) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateUpdatedAt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageGenerationUpsertOne) SetDeletedAt(v time.Time) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateDeletedAt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageGenerationUpsertOne) ClearDeletedAt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageGenerationUpsertOne) SetUserID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImageGenerationUpsertOne) AddUserID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateUserID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateUserID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ImageGenerationUpsertOne) SetConversationID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ImageGenerationUpsertOne) AddConversationID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateConversationID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateConversationID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ImageGenerationUpsertOne) SetGroupID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ImageGenerationUpsertOne) AddGroupID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateGroupID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateGroupID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *ImageGenerationUpsertOne) SetPrompt(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdatePrompt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdatePrompt()
	})
}

// SetModel sets the "model" field.
func (u *ImageGenerationUpsertOne) SetModel(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateModel() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateModel()
	})
}

// SetSize sets the "size" field.
func (u *ImageGenerationUpsertOne) SetSize(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateSize() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateSize()
	})
}

// SetQuality sets the "quality" field.
func (u *ImageGenerationUpsertOne) SetQuality(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetQuality(v)
	})
}

// UpdateQuality sets the "quality" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateQuality() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateQuality()
	})
}

// SetN sets the "n" field.
func (u *ImageGenerationUpsertOne) SetN(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetN(v)
	})
}

// AddN adds v to the "n" field.
func (u *ImageGenerationUpsertOne) AddN(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddN(v)
	})
}

// UpdateN sets the "n" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateN() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateN()
	})
}

// SetImageCount sets the "image_count" field.
func (u *ImageGenerationUpsertOne) SetImageCount(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetImageCount(v)
	})
}

// AddImageCount adds v to the "image_count" field.
func (u *ImageGenerationUpsertOne) AddImageCount(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddImageCount(v)
	})
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateImageCount() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateImageCount()
	})
}

// SetStatus sets the "status" field.
func (u *ImageGenerationUpsertOne) SetStatus(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateStatus() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateStatus()
	})
}

// SetCost sets the "cost" field.
func (u *ImageGenerationUpsertOne) SetCost(v float64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *ImageGenerationUpsertOne) AddCost(v float64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateCost() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateCost()
	})
}

// SetStorageKeys sets the "storage_keys" field.
func (u *ImageGenerationUpsertOne) SetStorageKeys(v []string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetStorageKeys(v)
	})
}

// UpdateStorageKeys sets the "storage_keys" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateStorageKeys() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateStorageKeys()
	})
}

// ClearStorageKeys clears the value of the "storage_keys" field.
func (u *ImageGenerationUpsertOne) ClearStorageKeys() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearStorageKeys()
	})
}

// SetInputStorageKeys sets the "input_storage_keys" field.
func (u *ImageGenerationUpsertOne) SetInputStorageKeys(v []string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetInputStorageKeys(v)
	})
}

// UpdateInputStorageKeys sets the "input_storage_keys" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateInputStorageKeys() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateInputStorageKeys()
	})
}

// ClearInputStorageKeys clears the value of the "input_storage_keys" field.
func (u *ImageGenerationUpsertOne) ClearInputStorageKeys() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearInputStorageKeys()
	})
}

// SetWidth sets the "width" field.
func (u *ImageGenerationUpsertOne) SetWidth(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageGenerationUpsertOne) AddWidth(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateWidth() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *ImageGenerationUpsertOne) ClearWidth() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageGenerationUpsertOne) SetHeight(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageGenerationUpsertOne) AddHeight(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateHeight() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *ImageGenerationUpsertOne) ClearHeight() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearHeight()
	})
}

// SetError sets the "error" field.
func (u *ImageGenerationUpsertOne) SetError(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateError() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *ImageGenerationUpsertOne) ClearError() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearError()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *ImageGenerationUpsertOne) SetErrorCode(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateErrorCode() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageGenerationUpsertOne) ClearErrorCode() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearErrorCode()
	})
}

// Exec executes the query.
func (u *ImageGenerationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageGenerationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageGenerationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageGenerationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageGenerationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageGenerationCreateBulk is the builder for creating many ImageGeneration entities in bulk.
type ImageGenerationCreateBulk struct {
	config
	err      error
	builders []*ImageGenerationCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageGeneration entities in the database.
func (_c *ImageGenerationCreateBulk) Save(ctx context.Context) ([]*ImageGeneration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageGeneration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageGenerationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageGenerationCreateBulk) SaveX(ctx context.Context) []*ImageGeneration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageGenerationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageGenerationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageGeneration.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageGenerationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageGenerationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageGenerationUpsertBulk {
	_c.conflict = opts
	return &ImageGenerationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageGenerationCreateBulk) OnConflictColumns(columns ...string) *ImageGenerationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageGenerationUpsertBulk{
		create: _c,
	}
}

// ImageGenerationUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageGeneration nodes.
type ImageGenerationUpsertBulk struct {
	create *ImageGenerationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageGenerationUpsertBulk) UpdateNewValues() *ImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imagegeneration.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageGenerationUpsertBulk) Ignore() *ImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageGenerationUpsertBulk) DoNothing() *ImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageGenerationCreateBulk.OnConflict
// documentation for more info.
func (u *ImageGenerationUpsertBulk) Update(set func(*ImageGenerationUpsert)) *ImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageGenerationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageGenerationUpsertBulk) SetUpdatedAt(v time.Time) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateUpdatedAt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageGenerationUpsertBulk) SetDeletedAt(v time.Time) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateDeletedAt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageGenerationUpsertBulk) ClearDeletedAt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageGenerationUpsertBulk) SetUserID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImageGenerationUpsertBulk) AddUserID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateUserID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateUserID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ImageGenerationUpsertBulk) SetConversationID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ImageGenerationUpsertBulk) AddConversationID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateConversationID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateConversationID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ImageGenerationUpsertBulk) SetGroupID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ImageGenerationUpsertBulk) AddGroupID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateGroupID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateGroupID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *ImageGenerationUpsertBulk) SetPrompt(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdatePrompt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdatePrompt()
	})
}

// SetModel sets the "model" field.
func (u *ImageGenerationUpsertBulk) SetModel(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateModel() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateModel()
	})
}

// SetSize sets the "size" field.
func (u *ImageGenerationUpsertBulk) SetSize(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateSize() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateSize()
	})
}

// SetQuality sets the "quality" field.
func (u *ImageGenerationUpsertBulk) SetQuality(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetQuality(v)
	})
}

// UpdateQuality sets the "quality" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateQuality() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateQuality()
	})
}

// SetN sets the "n" field.
func (u *ImageGenerationUpsertBulk) SetN(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetN(v)
	})
}

// AddN adds v to the "n" field.
func (u *ImageGenerationUpsertBulk) AddN(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddN(v)
	})
}

// UpdateN sets the "n" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateN() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateN()
	})
}

// SetImageCount sets the "image_count" field.
func (u *ImageGenerationUpsertBulk) SetImageCount(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetImageCount(v)
	})
}

// AddImageCount adds v to the "image_count" field.
func (u *ImageGenerationUpsertBulk) AddImageCount(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddImageCount(v)
	})
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateImageCount() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateImageCount()
	})
}

// SetStatus sets the "status" field.
func (u *ImageGenerationUpsertBulk) SetStatus(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateStatus() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateStatus()
	})
}

// SetCost sets the "cost" field.
func (u *ImageGenerationUpsertBulk) SetCost(v float64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *ImageGenerationUpsertBulk) AddCost(v float64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateCost() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateCost()
	})
}

// SetStorageKeys sets the "storage_keys" field.
func (u *ImageGenerationUpsertBulk) SetStorageKeys(v []string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetStorageKeys(v)
	})
}

// UpdateStorageKeys sets the "storage_keys" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateStorageKeys() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateStorageKeys()
	})
}

// ClearStorageKeys clears the value of the "storage_keys" field.
func (u *ImageGenerationUpsertBulk) ClearStorageKeys() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearStorageKeys()
	})
}

// SetInputStorageKeys sets the "input_storage_keys" field.
func (u *ImageGenerationUpsertBulk) SetInputStorageKeys(v []string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetInputStorageKeys(v)
	})
}

// UpdateInputStorageKeys sets the "input_storage_keys" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateInputStorageKeys() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateInputStorageKeys()
	})
}

// ClearInputStorageKeys clears the value of the "input_storage_keys" field.
func (u *ImageGenerationUpsertBulk) ClearInputStorageKeys() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearInputStorageKeys()
	})
}

// SetWidth sets the "width" field.
func (u *ImageGenerationUpsertBulk) SetWidth(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageGenerationUpsertBulk) AddWidth(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateWidth() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateWidth()
	})
}

// ClearWidth clears the value of the "width" field.
func (u *ImageGenerationUpsertBulk) ClearWidth() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageGenerationUpsertBulk) SetHeight(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageGenerationUpsertBulk) AddHeight(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateHeight() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateHeight()
	})
}

// ClearHeight clears the value of the "height" field.
func (u *ImageGenerationUpsertBulk) ClearHeight() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearHeight()
	})
}

// SetError sets the "error" field.
func (u *ImageGenerationUpsertBulk) SetError(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateError() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *ImageGenerationUpsertBulk) ClearError() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearError()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *ImageGenerationUpsertBulk) SetErrorCode(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateErrorCode() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageGenerationUpsertBulk) ClearErrorCode() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearErrorCode()
	})
}

// Exec executes the query.
func (u *ImageGenerationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageGenerationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageGenerationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageGenerationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
