// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videogeneration"
)

// VideoGenerationUpdate is the builder for updating VideoGeneration entities.
type VideoGenerationUpdate struct {
	config
	hooks    []Hook
	mutation *VideoGenerationMutation
}

// Where appends a list predicates to the VideoGenerationUpdate builder.
func (_u *VideoGenerationUpdate) Where(ps ...predicate.VideoGeneration) *VideoGenerationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoGenerationUpdate) SetUpdatedAt(v time.Time) *VideoGenerationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *VideoGenerationUpdate) SetDeletedAt(v time.Time) *VideoGenerationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableDeletedAt(v *time.Time) *VideoGenerationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *VideoGenerationUpdate) ClearDeletedAt() *VideoGenerationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoGenerationUpdate) SetUserID(v int64) *VideoGenerationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableUserID(v *int64) *VideoGenerationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *VideoGenerationUpdate) AddUserID(v int64) *VideoGenerationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoGenerationUpdate) SetGroupID(v int64) *VideoGenerationUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableGroupID(v *int64) *VideoGenerationUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *VideoGenerationUpdate) AddGroupID(v int64) *VideoGenerationUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *VideoGenerationUpdate) SetPrompt(v string) *VideoGenerationUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillablePrompt(v *string) *VideoGenerationUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *VideoGenerationUpdate) SetModel(v string) *VideoGenerationUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableModel(v *string) *VideoGenerationUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetOperationName sets the "operation_name" field.
func (_u *VideoGenerationUpdate) SetOperationName(v string) *VideoGenerationUpdate {
	_u.mutation.SetOperationName(v)
	return _u
}

// SetNillableOperationName sets the "operation_name" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableOperationName(v *string) *VideoGenerationUpdate {
	if v != nil {
		_u.SetOperationName(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoGenerationUpdate) SetAccountID(v int64) *VideoGenerationUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableAccountID(v *int64) *VideoGenerationUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *VideoGenerationUpdate) AddAccountID(v int64) *VideoGenerationUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoGenerationUpdate) SetStatus(v string) *VideoGenerationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableStatus(v *string) *VideoGenerationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSampleCount sets the "sample_count" field.
func (_u *VideoGenerationUpdate) SetSampleCount(v int) *VideoGenerationUpdate {
	_u.mutation.ResetSampleCount()
	_u.mutation.SetSampleCount(v)
	return _u
}

// SetNillableSampleCount sets the "sample_count" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableSampleCount(v *int) *VideoGenerationUpdate {
	if v != nil {
		_u.SetSampleCount(*v)
	}
	return _u
}

// AddSampleCount adds value to the "sample_count" field.
func (_u *VideoGenerationUpdate) AddSampleCount(v int) *VideoGenerationUpdate {
	_u.mutation.AddSampleCount(v)
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *VideoGenerationUpdate) SetDurationSeconds(v float64) *VideoGenerationUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableDurationSeconds(v *float64) *VideoGenerationUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *VideoGenerationUpdate) AddDurationSeconds(v float64) *VideoGenerationUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *VideoGenerationUpdate) SetCost(v float64) *VideoGenerationUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableCost(v *float64) *VideoGenerationUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *VideoGenerationUpdate) AddCost(v float64) *VideoGenerationUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetBilled sets the "billed" field.
func (_u *VideoGenerationUpdate) SetBilled(v bool) *VideoGenerationUpdate {
	_u.mutation.SetBilled(v)
	return _u
}

// SetNillableBilled sets the "billed" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableBilled(v *bool) *VideoGenerationUpdate {
	if v != nil {
		_u.SetBilled(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *VideoGenerationUpdate) SetError(v string) *VideoGenerationUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableError(v *string) *VideoGenerationUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *VideoGenerationUpdate) ClearError() *VideoGenerationUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *VideoGenerationUpdate) SetErrorCode(v string) *VideoGenerationUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *VideoGenerationUpdate) SetNillableErrorCode(v *string) *VideoGenerationUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *VideoGenerationUpdate) ClearErrorCode() *VideoGenerationUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// Mutation returns the VideoGenerationMutation object of the builder.
func (_u *VideoGenerationUpdate) Mutation() *VideoGenerationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoGenerationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoGenerationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoGenerationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoGenerationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoGenerationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if videogeneration.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized videogeneration.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := videogeneration.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoGenerationUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := videogeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationName(); ok {
		if err := videogeneration.OperationNameValidator(v); err != nil {
			return &ValidationError{Name: "operation_name", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.operation_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videogeneration.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := videogeneration.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoGenerationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videogeneration.Table, videogeneration.Columns, sqlgraph.NewFieldSpec(videogeneration.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videogeneration.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(videogeneration.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(videogeneration.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(videogeneration.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(videogeneration.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(videogeneration.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(videogeneration.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(videogeneration.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(videogeneration.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperationName(); ok {
		_spec.SetField(videogeneration.FieldOperationName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(videogeneration.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(videogeneration.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videogeneration.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SampleCount(); ok {
		_spec.SetField(videogeneration.FieldSampleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSampleCount(); ok {
		_spec.AddField(videogeneration.FieldSampleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(videogeneration.FieldDurationSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(videogeneration.FieldDurationSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(videogeneration.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(videogeneration.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Billed(); ok {
		_spec.SetField(videogeneration.FieldBilled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(videogeneration.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(videogeneration.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(videogeneration.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(videogeneration.FieldErrorCode, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videogeneration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoGenerationUpdateOne is the builder for updating a single VideoGeneration entity.
type VideoGenerationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoGenerationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoGenerationUpdateOne) SetUpdatedAt(v time.Time) *VideoGenerationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *VideoGenerationUpdateOne) SetDeletedAt(v time.Time) *VideoGenerationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableDeletedAt(v *time.Time) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *VideoGenerationUpdateOne) ClearDeletedAt() *VideoGenerationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoGenerationUpdateOne) SetUserID(v int64) *VideoGenerationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableUserID(v *int64) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *VideoGenerationUpdateOne) AddUserID(v int64) *VideoGenerationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoGenerationUpdateOne) SetGroupID(v int64) *VideoGenerationUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableGroupID(v *int64) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *VideoGenerationUpdateOne) AddGroupID(v int64) *VideoGenerationUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *VideoGenerationUpdateOne) SetPrompt(v string) *VideoGenerationUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillablePrompt(v *string) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *VideoGenerationUpdateOne) SetModel(v string) *VideoGenerationUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableModel(v *string) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetOperationName sets the "operation_name" field.
func (_u *VideoGenerationUpdateOne) SetOperationName(v string) *VideoGenerationUpdateOne {
	_u.mutation.SetOperationName(v)
	return _u
}

// SetNillableOperationName sets the "operation_name" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableOperationName(v *string) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetOperationName(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoGenerationUpdateOne) SetAccountID(v int64) *VideoGenerationUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableAccountID(v *int64) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *VideoGenerationUpdateOne) AddAccountID(v int64) *VideoGenerationUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoGenerationUpdateOne) SetStatus(v string) *VideoGenerationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableStatus(v *string) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSampleCount sets the "sample_count" field.
func (_u *VideoGenerationUpdateOne) SetSampleCount(v int) *VideoGenerationUpdateOne {
	_u.mutation.ResetSampleCount()
	_u.mutation.SetSampleCount(v)
	return _u
}

// SetNillableSampleCount sets the "sample_count" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableSampleCount(v *int) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetSampleCount(*v)
	}
	return _u
}

// AddSampleCount adds value to the "sample_count" field.
func (_u *VideoGenerationUpdateOne) AddSampleCount(v int) *VideoGenerationUpdateOne {
	_u.mutation.AddSampleCount(v)
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *VideoGenerationUpdateOne) SetDurationSeconds(v float64) *VideoGenerationUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableDurationSeconds(v *float64) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *VideoGenerationUpdateOne) AddDurationSeconds(v float64) *VideoGenerationUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *VideoGenerationUpdateOne) SetCost(v float64) *VideoGenerationUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableCost(v *float64) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *VideoGenerationUpdateOne) AddCost(v float64) *VideoGenerationUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetBilled sets the "billed" field.
func (_u *VideoGenerationUpdateOne) SetBilled(v bool) *VideoGenerationUpdateOne {
	_u.mutation.SetBilled(v)
	return _u
}

// SetNillableBilled sets the "billed" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableBilled(v *bool) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetBilled(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *VideoGenerationUpdateOne) SetError(v string) *VideoGenerationUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableError(v *string) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *VideoGenerationUpdateOne) ClearError() *VideoGenerationUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *VideoGenerationUpdateOne) SetErrorCode(v string) *VideoGenerationUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *VideoGenerationUpdateOne) SetNillableErrorCode(v *string) *VideoGenerationUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *VideoGenerationUpdateOne) ClearErrorCode() *VideoGenerationUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// Mutation returns the VideoGenerationMutation object of the builder.
func (_u *VideoGenerationUpdateOne) Mutation() *VideoGenerationMutation {
	return _u.mutation
}

// Where appends a list predicates to the VideoGenerationUpdate builder.
func (_u *VideoGenerationUpdateOne) Where(ps ...predicate.VideoGeneration) *VideoGenerationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoGenerationUpdateOne) Select(field string, fields ...string) *VideoGenerationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoGeneration entity.
func (_u *VideoGenerationUpdateOne) Save(ctx context.Context) (*VideoGeneration, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoGenerationUpdateOne) SaveX(ctx context.Context) *VideoGeneration {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoGenerationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoGenerationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoGenerationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if videogeneration.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized videogeneration.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := videogeneration.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoGenerationUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := videogeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationName(); ok {
		if err := videogeneration.OperationNameValidator(v); err != nil {
			return &ValidationError{Name: "operation_name", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.operation_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videogeneration.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := videogeneration.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoGenerationUpdateOne) sqlSave(ctx context.Context) (_node *VideoGeneration, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videogeneration.Table, videogeneration.Columns, sqlgraph.NewFieldSpec(videogeneration.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoGeneration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videogeneration.FieldID)
		for _, f := range fields {
			if !videogeneration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videogeneration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videogeneration.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(videogeneration.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(videogeneration.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(videogeneration.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(videogeneration.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(videogeneration.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(videogeneration.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(videogeneration.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(videogeneration.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperationName(); ok {
		_spec.SetField(videogeneration.FieldOperationName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(videogeneration.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(videogeneration.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videogeneration.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SampleCount(); ok {
		_spec.SetField(videogeneration.FieldSampleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSampleCount(); ok {
		_spec.AddField(videogeneration.FieldSampleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(videogeneration.FieldDurationSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(videogeneration.FieldDurationSeconds, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(videogeneration.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(videogeneration.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Billed(); ok {
		_spec.SetField(videogeneration.FieldBilled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(videogeneration.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(videogeneration.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(videogeneration.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(videogeneration.FieldErrorCode, field.TypeString)
	}
	_node = &VideoGeneration{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videogeneration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
