// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/videogeneration"
)

// VideoGenerationCreate is the builder for creating a VideoGeneration entity.
type VideoGenerationCreate struct {
	config
	mutation *VideoGenerationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoGenerationCreate) SetCreatedAt(v time.Time) *VideoGenerationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableCreatedAt(v *time.Time) *VideoGenerationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoGenerationCreate) SetUpdatedAt(v time.Time) *VideoGenerationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableUpdatedAt(v *time.Time) *VideoGenerationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *VideoGenerationCreate) SetDeletedAt(v time.Time) *VideoGenerationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableDeletedAt(v *time.Time) *VideoGenerationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VideoGenerationCreate) SetUserID(v int64) *VideoGenerationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *VideoGenerationCreate) SetGroupID(v int64) *VideoGenerationCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *VideoGenerationCreate) SetPrompt(v string) *VideoGenerationCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *VideoGenerationCreate) SetModel(v string) *VideoGenerationCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableModel(v *string) *VideoGenerationCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetOperationName sets the "operation_name" field.
func (_c *VideoGenerationCreate) SetOperationName(v string) *VideoGenerationCreate {
	_c.mutation.SetOperationName(v)
	return _c
}

// SetNillableOperationName sets the "operation_name" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableOperationName(v *string) *VideoGenerationCreate {
	if v != nil {
		_c.SetOperationName(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *VideoGenerationCreate) SetAccountID(v int64) *VideoGenerationCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableAccountID(v *int64) *VideoGenerationCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *VideoGenerationCreate) SetStatus(v string) *VideoGenerationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableStatus(v *string) *VideoGenerationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSampleCount sets the "sample_count" field.
func (_c *VideoGenerationCreate) SetSampleCount(v int) *VideoGenerationCreate {
	_c.mutation.SetSampleCount(v)
	return _c
}

// SetNillableSampleCount sets the "sample_count" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableSampleCount(v *int) *VideoGenerationCreate {
	if v != nil {
		_c.SetSampleCount(*v)
	}
	return _c
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_c *VideoGenerationCreate) SetDurationSeconds(v float64) *VideoGenerationCreate {
	_c.mutation.SetDurationSeconds(v)
	return _c
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableDurationSeconds(v *float64) *VideoGenerationCreate {
	if v != nil {
		_c.SetDurationSeconds(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *VideoGenerationCreate) SetCost(v float64) *VideoGenerationCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableCost(v *float64) *VideoGenerationCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetBilled sets the "billed" field.
func (_c *VideoGenerationCreate) SetBilled(v bool) *VideoGenerationCreate {
	_c.mutation.SetBilled(v)
	return _c
}

// SetNillableBilled sets the "billed" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableBilled(v *bool) *VideoGenerationCreate {
	if v != nil {
		_c.SetBilled(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *VideoGenerationCreate) SetError(v string) *VideoGenerationCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableError(v *string) *VideoGenerationCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *VideoGenerationCreate) SetErrorCode(v string) *VideoGenerationCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *VideoGenerationCreate) SetNillableErrorCode(v *string) *VideoGenerationCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// Mutation returns the VideoGenerationMutation object of the builder.
func (_c *VideoGenerationCreate) Mutation() *VideoGenerationMutation {
	return _c.mutation
}

// Save creates the VideoGeneration in the database.
func (_c *VideoGenerationCreate) Save(ctx context.Context) (*VideoGeneration, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoGenerationCreate) SaveX(ctx context.Context) *VideoGeneration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoGenerationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoGenerationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoGenerationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if videogeneration.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized videogeneration.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := videogeneration.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if videogeneration.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized videogeneration.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := videogeneration.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := videogeneration.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.OperationName(); !ok {
		v := videogeneration.DefaultOperationName
		_c.mutation.SetOperationName(v)
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		v := videogeneration.DefaultAccountID
		_c.mutation.SetAccountID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := videogeneration.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SampleCount(); !ok {
		v := videogeneration.DefaultSampleCount
		_c.mutation.SetSampleCount(v)
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		v := videogeneration.DefaultDurationSeconds
		_c.mutation.SetDurationSeconds(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := videogeneration.DefaultCost
		_c.mutation.SetCost(v)
	}
	if _, ok := _c.mutation.Billed(); !ok {
		v := videogeneration.DefaultBilled
		_c.mutation.SetBilled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoGenerationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoGeneration.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoGeneration.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VideoGeneration.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "VideoGeneration.group_id"`)}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "VideoGeneration.prompt"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "VideoGeneration.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := videogeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OperationName(); !ok {
		return &ValidationError{Name: "operation_name", err: errors.New(`ent: missing required field "VideoGeneration.operation_name"`)}
	}
	if v, ok := _c.mutation.OperationName(); ok {
		if err := videogeneration.OperationNameValidator(v); err != nil {
			return &ValidationError{Name: "operation_name", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.operation_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "VideoGeneration.account_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VideoGeneration.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := videogeneration.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SampleCount(); !ok {
		return &ValidationError{Name: "sample_count", err: errors.New(`ent: missing required field "VideoGeneration.sample_count"`)}
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		return &ValidationError{Name: "duration_seconds", err: errors.New(`ent: missing required field "VideoGeneration.duration_seconds"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "VideoGeneration.cost"`)}
	}
	if _, ok := _c.mutation.Billed(); !ok {
		return &ValidationError{Name: "billed", err: errors.New(`ent: missing required field "VideoGeneration.billed"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := videogeneration.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "VideoGeneration.error_code": %w`, err)}
		}
	}
	return nil
}

func (_c *VideoGenerationCreate) sqlSave(ctx context.Context) (*VideoGeneration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoGenerationCreate) createSpec() (*VideoGeneration, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoGeneration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videogeneration.Table, sqlgraph.NewFieldSpec(videogeneration.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videogeneration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videogeneration.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(videogeneration.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(videogeneration.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(videogeneration.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(videogeneration.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(videogeneration.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.OperationName(); ok {
		_spec.SetField(videogeneration.FieldOperationName, field.TypeString, value)
		_node.OperationName = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(videogeneration.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(videogeneration.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SampleCount(); ok {
		_spec.SetField(videogeneration.FieldSampleCount, field.TypeInt, value)
		_node.SampleCount = value
	}
	if value, ok := _c.mutation.DurationSeconds(); ok {
		_spec.SetField(videogeneration.FieldDurationSeconds, field.TypeFloat64, value)
		_node.DurationSeconds = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(videogeneration.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Billed(); ok {
		_spec.SetField(videogeneration.FieldBilled, field.TypeBool, value)
		_node.Billed = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(videogeneration.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(videogeneration.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoGeneration.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoGenerationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoGenerationCreate) OnConflict(opts ...sql.ConflictOption) *VideoGenerationUpsertOne {
	_c.conflict = opts
	return &VideoGenerationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoGeneration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoGenerationCreate) OnConflictColumns(columns ...string) *VideoGenerationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoGenerationUpsertOne{
		create: _c,
	}
}

type (
	// VideoGenerationUpsertOne is the builder for "upsert"-ing
	//  one VideoGeneration node.
	VideoGenerationUpsertOne struct {
		create *VideoGenerationCreate
	}

	// VideoGenerationUpsert is the "OnConflict" setter.
	VideoGenerationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoGenerationUpsert) SetUpdatedAt(v time.Time) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateUpdatedAt() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *VideoGenerationUpsert) SetDeletedAt(v time.Time) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateDeletedAt() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *VideoGenerationUpsert) ClearDeletedAt() *VideoGenerationUpsert {
	u.SetNull(videogeneration.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *VideoGenerationUpsert) SetUserID(v int64) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateUserID() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *VideoGenerationUpsert) AddUserID(v int64) *VideoGenerationUpsert {
	u.Add(videogeneration.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *VideoGenerationUpsert) SetGroupID(v int64) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateGroupID() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *VideoGenerationUpsert) AddGroupID(v int64) *VideoGenerationUpsert {
	u.Add(videogeneration.FieldGroupID, v)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *VideoGenerationUpsert) SetPrompt(v string) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdatePrompt() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldPrompt)
	return u
}

// SetModel sets the "model" field.
func (u *VideoGenerationUpsert) SetModel(v string) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateModel() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldModel)
	return u
}

// SetOperationName sets the "operation_name" field.
func (u *VideoGenerationUpsert) SetOperationName(v string) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldOperationName, v)
	return u
}

// UpdateOperationName sets the "operation_name" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateOperationName() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldOperationName)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *VideoGenerationUpsert) SetAccountID(v int64) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateAccountID() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoGenerationUpsert) AddAccountID(v int64) *VideoGenerationUpsert {
	u.Add(videogeneration.FieldAccountID, v)
	return u
}

// SetStatus sets the "status" field.
func (u *VideoGenerationUpsert) SetStatus(v string) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateStatus() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldStatus)
	return u
}

// SetSampleCount sets the "sample_count" field.
func (u *VideoGenerationUpsert) SetSampleCount(v int) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldSampleCount, v)
	return u
}

// UpdateSampleCount sets the "sample_count" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateSampleCount() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldSampleCount)
	return u
}

// AddSampleCount adds v to the "sample_count" field.
func (u *VideoGenerationUpsert) AddSampleCount(v int) *VideoGenerationUpsert {
	u.Add(videogeneration.FieldSampleCount, v)
	return u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VideoGenerationUpsert) SetDurationSeconds(v float64) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldDurationSeconds, v)
	return u
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateDurationSeconds() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldDurationSeconds)
	return u
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VideoGenerationUpsert) AddDurationSeconds(v float64) *VideoGenerationUpsert {
	u.Add(videogeneration.FieldDurationSeconds, v)
	return u
}

// SetCost sets the "cost" field.
func (u *VideoGenerationUpsert) SetCost(v float64) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateCost() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *VideoGenerationUpsert) AddCost(v float64) *VideoGenerationUpsert {
	u.Add(videogeneration.FieldCost, v)
	return u
}

// SetBilled sets the "billed" field.
func (u *VideoGenerationUpsert) SetBilled(v bool) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldBilled, v)
	return u
}

// UpdateBilled sets the "billed" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateBilled() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldBilled)
	return u
}

// SetError sets the "error" field.
func (u *VideoGenerationUpsert) SetError(v string) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateError() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *VideoGenerationUpsert) ClearError() *VideoGenerationUpsert {
	u.SetNull(videogeneration.FieldError)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *VideoGenerationUpsert) SetErrorCode(v string) *VideoGenerationUpsert {
	u.Set(videogeneration.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *VideoGenerationUpsert) UpdateErrorCode() *VideoGenerationUpsert {
	u.SetExcluded(videogeneration.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *VideoGenerationUpsert) ClearErrorCode() *VideoGenerationUpsert {
	u.SetNull(videogeneration.FieldErrorCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoGeneration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoGenerationUpsertOne) UpdateNewValues() *VideoGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videogeneration.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoGeneration.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoGenerationUpsertOne) Ignore() *VideoGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoGenerationUpsertOne) DoNothing() *VideoGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoGenerationCreate.OnConflict
// documentation for more info.
func (u *VideoGenerationUpsertOne) Update(set func(*VideoGenerationUpsert)) *VideoGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoGenerationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoGenerationUpsertOne) SetUpdatedAt(v time.Time) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateUpdatedAt() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *VideoGenerationUpsertOne) SetDeletedAt(v time.Time) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateDeletedAt() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *VideoGenerationUpsertOne) ClearDeletedAt() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *VideoGenerationUpsertOne) SetUserID(v int64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *VideoGenerationUpsertOne) AddUserID(v int64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateUserID() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *VideoGenerationUpsertOne) SetGroupID(v int64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *VideoGenerationUpsertOne) AddGroupID(v int64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateGroupID() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateGroupID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *VideoGenerationUpsertOne) SetPrompt(v string) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdatePrompt() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdatePrompt()
	})
}

// SetModel sets the "model" field.
func (u *VideoGenerationUpsertOne) SetModel(v string) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateModel() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateModel()
	})
}

// SetOperationName sets the "operation_name" field.
func (u *VideoGenerationUpsertOne) SetOperationName(v string) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetOperationName(v)
	})
}

// UpdateOperationName sets the "operation_name" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateOperationName() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateOperationName()
	})
}

// SetAccountID sets the "account_id" field.
func (u *VideoGenerationUpsertOne) SetAccountID(v int64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoGenerationUpsertOne) AddAccountID(v int64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateAccountID() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateAccountID()
	})
}

// SetStatus sets the "status" field.
func (u *VideoGenerationUpsertOne) SetStatus(v string) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateStatus() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateStatus()
	})
}

// SetSampleCount sets the "sample_count" field.
func (u *VideoGenerationUpsertOne) SetSampleCount(v int) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetSampleCount(v)
	})
}

// AddSampleCount adds v to the "sample_count" field.
func (u *VideoGenerationUpsertOne) AddSampleCount(v int) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddSampleCount(v)
	})
}

// UpdateSampleCount sets the "sample_count" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateSampleCount() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateSampleCount()
	})
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VideoGenerationUpsertOne) SetDurationSeconds(v float64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetDurationSeconds(v)
	})
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VideoGenerationUpsertOne) AddDurationSeconds(v float64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddDurationSeconds(v)
	})
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateDurationSeconds() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateDurationSeconds()
	})
}

// SetCost sets the "cost" field.
func (u *VideoGenerationUpsertOne) SetCost(v float64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *VideoGenerationUpsertOne) AddCost(v float64) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateCost() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateCost()
	})
}

// SetBilled sets the "billed" field.
func (u *VideoGenerationUpsertOne) SetBilled(v bool) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetBilled(v)
	})
}

// UpdateBilled sets the "billed" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateBilled() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateBilled()
	})
}

// SetError sets the "error" field.
func (u *VideoGenerationUpsertOne) SetError(v string) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateError() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *VideoGenerationUpsertOne) ClearError() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.ClearError()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *VideoGenerationUpsertOne) SetErrorCode(v string) *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *VideoGenerationUpsertOne) UpdateErrorCode() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *VideoGenerationUpsertOne) ClearErrorCode() *VideoGenerationUpsertOne {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.ClearErrorCode()
	})
}

// Exec executes the query.
func (u *VideoGenerationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoGenerationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoGenerationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoGenerationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoGenerationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoGenerationCreateBulk is the builder for creating many VideoGeneration entities in bulk.
type VideoGenerationCreateBulk struct {
	config
	err      error
	builders []*VideoGenerationCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoGeneration entities in the database.
func (_c *VideoGenerationCreateBulk) Save(ctx context.Context) ([]*VideoGeneration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoGeneration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoGenerationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoGenerationCreateBulk) SaveX(ctx context.Context) []*VideoGeneration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoGenerationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoGenerationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoGeneration.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoGenerationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoGenerationCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoGenerationUpsertBulk {
	_c.conflict = opts
	return &VideoGenerationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoGeneration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoGenerationCreateBulk) OnConflictColumns(columns ...string) *VideoGenerationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoGenerationUpsertBulk{
		create: _c,
	}
}

// VideoGenerationUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoGeneration nodes.
type VideoGenerationUpsertBulk struct {
	create *VideoGenerationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoGeneration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoGenerationUpsertBulk) UpdateNewValues() *VideoGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videogeneration.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoGeneration.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoGenerationUpsertBulk) Ignore() *VideoGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoGenerationUpsertBulk) DoNothing() *VideoGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoGenerationCreateBulk.OnConflict
// documentation for more info.
func (u *VideoGenerationUpsertBulk) Update(set func(*VideoGenerationUpsert)) *VideoGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoGenerationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoGenerationUpsertBulk) SetUpdatedAt(v time.Time) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateUpdatedAt() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *VideoGenerationUpsertBulk) SetDeletedAt(v time.Time) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateDeletedAt() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *VideoGenerationUpsertBulk) ClearDeletedAt() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *VideoGenerationUpsertBulk) SetUserID(v int64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *VideoGenerationUpsertBulk) AddUserID(v int64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateUserID() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *VideoGenerationUpsertBulk) SetGroupID(v int64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *VideoGenerationUpsertBulk) AddGroupID(v int64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateGroupID() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateGroupID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *VideoGenerationUpsertBulk) SetPrompt(v string) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdatePrompt() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdatePrompt()
	})
}

// SetModel sets the "model" field.
func (u *VideoGenerationUpsertBulk) SetModel(v string) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateModel() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateModel()
	})
}

// SetOperationName sets the "operation_name" field.
func (u *VideoGenerationUpsertBulk) SetOperationName(v string) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetOperationName(v)
	})
}

// UpdateOperationName sets the "operation_name" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateOperationName() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateOperationName()
	})
}

// SetAccountID sets the "account_id" field.
func (u *VideoGenerationUpsertBulk) SetAccountID(v int64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoGenerationUpsertBulk) AddAccountID(v int64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateAccountID() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateAccountID()
	})
}

// SetStatus sets the "status" field.
func (u *VideoGenerationUpsertBulk) SetStatus(v string) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateStatus() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateStatus()
	})
}

// SetSampleCount sets the "sample_count" field.
func (u *VideoGenerationUpsertBulk) SetSampleCount(v int) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetSampleCount(v)
	})
}

// AddSampleCount adds v to the "sample_count" field.
func (u *VideoGenerationUpsertBulk) AddSampleCount(v int) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddSampleCount(v)
	})
}

// UpdateSampleCount sets the "sample_count" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateSampleCount() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateSampleCount()
	})
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VideoGenerationUpsertBulk) SetDurationSeconds(v float64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetDurationSeconds(v)
	})
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VideoGenerationUpsertBulk) AddDurationSeconds(v float64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddDurationSeconds(v)
	})
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateDurationSeconds() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateDurationSeconds()
	})
}

// SetCost sets the "cost" field.
func (u *VideoGenerationUpsertBulk) SetCost(v float64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *VideoGenerationUpsertBulk) AddCost(v float64) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateCost() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateCost()
	})
}

// SetBilled sets the "billed" field.
func (u *VideoGenerationUpsertBulk) SetBilled(v bool) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetBilled(v)
	})
}

// UpdateBilled sets the "billed" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateBilled() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateBilled()
	})
}

// SetError sets the "error" field.
func (u *VideoGenerationUpsertBulk) SetError(v string) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateError() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *VideoGenerationUpsertBulk) ClearError() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.ClearError()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *VideoGenerationUpsertBulk) SetErrorCode(v string) *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *VideoGenerationUpsertBulk) UpdateErrorCode() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *VideoGenerationUpsertBulk) ClearErrorCode() *VideoGenerationUpsertBulk {
	return u.Update(func(s *VideoGenerationUpsert) {
		s.ClearErrorCode()
	})
}

// Exec executes the query.
func (u *VideoGenerationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoGenerationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoGenerationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoGenerationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
