// Code generated by ent, DO NOT EDIT.

package editablefileartifact

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldDeletedAt, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldTaskID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldUserID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldKind, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldFileName, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldMimeType, v))
}

// SizeBytes applies equality check predicate on the "size_bytes" field. It's identical to SizeBytesEQ.
func SizeBytes(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldSizeBytes, v))
}

// StorageKey applies equality check predicate on the "storage_key" field. It's identical to StorageKeyEQ.
func StorageKey(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldStorageKey, v))
}

// SourcePointer applies equality check predicate on the "source_pointer" field. It's identical to SourcePointerEQ.
func SourcePointer(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldSourcePointer, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldSha256, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotNull(FieldDeletedAt))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldTaskID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldUserID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContainsFold(FieldKind, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContainsFold(FieldFileName, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContainsFold(FieldMimeType, v))
}

// SizeBytesEQ applies the EQ predicate on the "size_bytes" field.
func SizeBytesEQ(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldSizeBytes, v))
}

// SizeBytesNEQ applies the NEQ predicate on the "size_bytes" field.
func SizeBytesNEQ(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldSizeBytes, v))
}

// SizeBytesIn applies the In predicate on the "size_bytes" field.
func SizeBytesIn(vs ...int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldSizeBytes, vs...))
}

// SizeBytesNotIn applies the NotIn predicate on the "size_bytes" field.
func SizeBytesNotIn(vs ...int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldSizeBytes, vs...))
}

// SizeBytesGT applies the GT predicate on the "size_bytes" field.
func SizeBytesGT(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldSizeBytes, v))
}

// SizeBytesGTE applies the GTE predicate on the "size_bytes" field.
func SizeBytesGTE(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldSizeBytes, v))
}

// SizeBytesLT applies the LT predicate on the "size_bytes" field.
func SizeBytesLT(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldSizeBytes, v))
}

// SizeBytesLTE applies the LTE predicate on the "size_bytes" field.
func SizeBytesLTE(v int64) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldSizeBytes, v))
}

// StorageKeyEQ applies the EQ predicate on the "storage_key" field.
func StorageKeyEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldStorageKey, v))
}

// StorageKeyNEQ applies the NEQ predicate on the "storage_key" field.
func StorageKeyNEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldStorageKey, v))
}

// StorageKeyIn applies the In predicate on the "storage_key" field.
func StorageKeyIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldStorageKey, vs...))
}

// StorageKeyNotIn applies the NotIn predicate on the "storage_key" field.
func StorageKeyNotIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldStorageKey, vs...))
}

// StorageKeyGT applies the GT predicate on the "storage_key" field.
func StorageKeyGT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldStorageKey, v))
}

// StorageKeyGTE applies the GTE predicate on the "storage_key" field.
func StorageKeyGTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldStorageKey, v))
}

// StorageKeyLT applies the LT predicate on the "storage_key" field.
func StorageKeyLT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldStorageKey, v))
}

// StorageKeyLTE applies the LTE predicate on the "storage_key" field.
func StorageKeyLTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldStorageKey, v))
}

// StorageKeyContains applies the Contains predicate on the "storage_key" field.
func StorageKeyContains(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContains(FieldStorageKey, v))
}

// StorageKeyHasPrefix applies the HasPrefix predicate on the "storage_key" field.
func StorageKeyHasPrefix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasPrefix(FieldStorageKey, v))
}

// StorageKeyHasSuffix applies the HasSuffix predicate on the "storage_key" field.
func StorageKeyHasSuffix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasSuffix(FieldStorageKey, v))
}

// StorageKeyEqualFold applies the EqualFold predicate on the "storage_key" field.
func StorageKeyEqualFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEqualFold(FieldStorageKey, v))
}

// StorageKeyContainsFold applies the ContainsFold predicate on the "storage_key" field.
func StorageKeyContainsFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContainsFold(FieldStorageKey, v))
}

// SourcePointerEQ applies the EQ predicate on the "source_pointer" field.
func SourcePointerEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldSourcePointer, v))
}

// SourcePointerNEQ applies the NEQ predicate on the "source_pointer" field.
func SourcePointerNEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldSourcePointer, v))
}

// SourcePointerIn applies the In predicate on the "source_pointer" field.
func SourcePointerIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldSourcePointer, vs...))
}

// SourcePointerNotIn applies the NotIn predicate on the "source_pointer" field.
func SourcePointerNotIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldSourcePointer, vs...))
}

// SourcePointerGT applies the GT predicate on the "source_pointer" field.
func SourcePointerGT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldSourcePointer, v))
}

// SourcePointerGTE applies the GTE predicate on the "source_pointer" field.
func SourcePointerGTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldSourcePointer, v))
}

// SourcePointerLT applies the LT predicate on the "source_pointer" field.
func SourcePointerLT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldSourcePointer, v))
}

// SourcePointerLTE applies the LTE predicate on the "source_pointer" field.
func SourcePointerLTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldSourcePointer, v))
}

// SourcePointerContains applies the Contains predicate on the "source_pointer" field.
func SourcePointerContains(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContains(FieldSourcePointer, v))
}

// SourcePointerHasPrefix applies the HasPrefix predicate on the "source_pointer" field.
func SourcePointerHasPrefix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasPrefix(FieldSourcePointer, v))
}

// SourcePointerHasSuffix applies the HasSuffix predicate on the "source_pointer" field.
func SourcePointerHasSuffix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasSuffix(FieldSourcePointer, v))
}

// SourcePointerIsNil applies the IsNil predicate on the "source_pointer" field.
func SourcePointerIsNil() predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIsNull(FieldSourcePointer))
}

// SourcePointerNotNil applies the NotNil predicate on the "source_pointer" field.
func SourcePointerNotNil() predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotNull(FieldSourcePointer))
}

// SourcePointerEqualFold applies the EqualFold predicate on the "source_pointer" field.
func SourcePointerEqualFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEqualFold(FieldSourcePointer, v))
}

// SourcePointerContainsFold applies the ContainsFold predicate on the "source_pointer" field.
func SourcePointerContainsFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContainsFold(FieldSourcePointer, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.FieldContainsFold(FieldSha256, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EditableFileArtifact) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EditableFileArtifact) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EditableFileArtifact) predicate.EditableFileArtifact {
	return predicate.EditableFileArtifact(sql.NotPredicates(p))
}
