// Code generated by ent, DO NOT EDIT.

package videogeneration

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldGroupID, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldPrompt, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldModel, v))
}

// OperationName applies equality check predicate on the "operation_name" field. It's identical to OperationNameEQ.
func OperationName(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldOperationName, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldAccountID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldStatus, v))
}

// SampleCount applies equality check predicate on the "sample_count" field. It's identical to SampleCountEQ.
func SampleCount(v int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldSampleCount, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldDurationSeconds, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldCost, v))
}

// Billed applies equality check predicate on the "billed" field. It's identical to BilledEQ.
func Billed(v bool) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldBilled, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldError, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldErrorCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldGroupID, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContainsFold(FieldPrompt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContainsFold(FieldModel, v))
}

// OperationNameEQ applies the EQ predicate on the "operation_name" field.
func OperationNameEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldOperationName, v))
}

// OperationNameNEQ applies the NEQ predicate on the "operation_name" field.
func OperationNameNEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldOperationName, v))
}

// OperationNameIn applies the In predicate on the "operation_name" field.
func OperationNameIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldOperationName, vs...))
}

// OperationNameNotIn applies the NotIn predicate on the "operation_name" field.
func OperationNameNotIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldOperationName, vs...))
}

// OperationNameGT applies the GT predicate on the "operation_name" field.
func OperationNameGT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldOperationName, v))
}

// OperationNameGTE applies the GTE predicate on the "operation_name" field.
func OperationNameGTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldOperationName, v))
}

// OperationNameLT applies the LT predicate on the "operation_name" field.
func OperationNameLT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldOperationName, v))
}

// OperationNameLTE applies the LTE predicate on the "operation_name" field.
func OperationNameLTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldOperationName, v))
}

// OperationNameContains applies the Contains predicate on the "operation_name" field.
func OperationNameContains(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContains(FieldOperationName, v))
}

// OperationNameHasPrefix applies the HasPrefix predicate on the "operation_name" field.
func OperationNameHasPrefix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasPrefix(FieldOperationName, v))
}

// OperationNameHasSuffix applies the HasSuffix predicate on the "operation_name" field.
func OperationNameHasSuffix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasSuffix(FieldOperationName, v))
}

// OperationNameEqualFold applies the EqualFold predicate on the "operation_name" field.
func OperationNameEqualFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEqualFold(FieldOperationName, v))
}

// OperationNameContainsFold applies the ContainsFold predicate on the "operation_name" field.
func OperationNameContainsFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContainsFold(FieldOperationName, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldAccountID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContainsFold(FieldStatus, v))
}

// SampleCountEQ applies the EQ predicate on the "sample_count" field.
func SampleCountEQ(v int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldSampleCount, v))
}

// SampleCountNEQ applies the NEQ predicate on the "sample_count" field.
func SampleCountNEQ(v int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldSampleCount, v))
}

// SampleCountIn applies the In predicate on the "sample_count" field.
func SampleCountIn(vs ...int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldSampleCount, vs...))
}

// SampleCountNotIn applies the NotIn predicate on the "sample_count" field.
func SampleCountNotIn(vs ...int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldSampleCount, vs...))
}

// SampleCountGT applies the GT predicate on the "sample_count" field.
func SampleCountGT(v int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldSampleCount, v))
}

// SampleCountGTE applies the GTE predicate on the "sample_count" field.
func SampleCountGTE(v int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldSampleCount, v))
}

// SampleCountLT applies the LT predicate on the "sample_count" field.
func SampleCountLT(v int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldSampleCount, v))
}

// SampleCountLTE applies the LTE predicate on the "sample_count" field.
func SampleCountLTE(v int) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldSampleCount, v))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldDurationSeconds, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v float64) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldCost, v))
}

// BilledEQ applies the EQ predicate on the "billed" field.
func BilledEQ(v bool) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldBilled, v))
}

// BilledNEQ applies the NEQ predicate on the "billed" field.
func BilledNEQ(v bool) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldBilled, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContainsFold(FieldError, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.FieldContainsFold(FieldErrorCode, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VideoGeneration) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VideoGeneration) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VideoGeneration) predicate.VideoGeneration {
	return predicate.VideoGeneration(sql.NotPredicates(p))
}
